composer.patches.json
config/core.extension.yml
config/views.view.moderated_content.yml
config/workflows.workflow.announcement.yml
config/workflows.workflow.blog_post.yml
config/workflows.workflow.book.yml
config/workflows.workflow.country.yml
config/workflows.workflow.disaster.yml
config/workflows.workflow.job.yml
config/workflows.workflow.report.yml
config/workflows.workflow.source.yml
config/workflows.workflow.topic.yml
config/workflows.workflow.training.yml
patches/core--drupal--3047110-taxonomy-term-moderation-class.patch

Ticket: RW-26
This enables the `content_moderation` module and adds workflows with moderation statuses to the relevant nodes and terms.

[RW-26] Add moderation statuses for nodes and terms

---

html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-country-slug.html.twig
html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-meta.html.twig
html/modules/custom/reliefweb_homepage/templates/reliefweb-homepage-announcement.html.twig
html/modules/custom/reliefweb_homepage/templates/reliefweb-homepage-opportunities.html.twig
html/modules/custom/reliefweb_homepage/templates/reliefweb-homepage.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-country-list.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--blog-post.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--disaster.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article-title.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-entities/reliefweb-entities-entity-country-slug.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-entities/reliefweb-entities-entity-meta.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-homepage/reliefweb-homepage-announcement.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-homepage/reliefweb-homepage-opportunities.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-homepage/reliefweb-homepage.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-river-article--blog-post.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-river-article--disaster.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-river-article-title.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-river.html.twig

Remove twig blocks for library attachment in custom module templates
And replace the Twig embed with Twig include for sub theme template overrides

RW-31 Adjust template overrides to use twig include instead of embed

---

html/modules/custom/reliefweb_api/src/Services/ReliefWebApiClient.php
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/src/BundleEntityInterface.php
html/modules/custom/reliefweb_entities/src/Entity/Country.php
html/modules/custom/reliefweb_entities/src/Entity/Disaster.php
html/modules/custom/reliefweb_entities/src/Entity/Source.php
html/modules/custom/reliefweb_entities/src/SectionedContentInterface.php
html/modules/custom/reliefweb_entities/src/SectionedContentTrait.php
html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-useful-links.html.twig
html/modules/custom/reliefweb_homepage/src/Controller/Homepage.php
html/modules/custom/reliefweb_rivers/src/RiverServiceBase.php
html/modules/custom/reliefweb_rivers/src/RiverServiceInterface.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--report.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river.html.twig
html/modules/custom/reliefweb_utility/src/Helpers/HtmlSanitizer.php

Tickets: [RW-24][RW-28]
This adds the Key Content, Appeals and Useful Links sections to the country and disaster pages. 
Note: this uses the API to get those profile fields and after the actual fields are ported, will use them.
This PR also does some code shuffling to reduce duplication by having the homepage, country and disaster pages get the API payload for their sections from the river services.
[RW-24]: https://humanitarian.atlassian.net/browse/RW-24
[RW-28]: https://humanitarian.atlassian.net/browse/RW-28

[RW-24][RW-28] Key Content, Appeals and Useful Links

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-meta.html.twig

Ticket: RW-34
This adds a flag to the "entity-meta" template to add a class to distinguish the "core" meta information in river articles and below the title on article pages from the "full" meta information in the sidebar of the article pages.

[RW-34] Add class for core meta

---

html/themes/custom/common_design_subtheme/components/rw-dsr/rw-dsr.css

Ticket: RW-47
This fixes the "with illustration" rules to use the `rw-dsr--with-illustration` class.
Added a `@todo` about the space between the section title and the content. There is a follow-up ticket for that: RW-55.

[RW-47] Enable display of DSR illustation on desktop

---

html/themes/custom/common_design_subtheme/components/rw-disasters/rw-disasters.css
html/themes/custom/common_design_subtheme/components/rw-homepage/rw-homepage.css

Ticket: RW-63, RW-38
This changes the selectors in `rw-disasters` to ensure the disaster icons are displayed in all the disaster rivers.
The special rules for the homepage have been moved to `rw-homepage`.

[RW-63] Ensure the disaster icons are displayed in all the disaster rivers

---

html/modules/custom/reliefweb_rivers/src/RiverServiceBase.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-page.html.twig

Ticket: RW-60
This displays the river page title when there are no `views` to ensure we know on which page we are.
Note: this PR doesn't style this page title. Follow-up ticket for that: RW-68.

[RW-60] Display river page title when there are no alternative views

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/rw-river-letter-navigation/rw-river-letter-navigation.css
html/themes/custom/common_design_subtheme/components/rw-river-letter-navigation/rw-river-letter-navigation.js

Ticket: RW-59
This adds back a piece of [javascript](https://github.com/UN-OCHA/rwint-site/blob/bfb100de099df2c02a2319e7e2b5af0e3c12b484/site/profiles/reliefweb/themes/kobe/js/site.js#L12-L28) that was used to style the active link in the /countries river page. 
It also updates the CSS rule to style this active link which was before using [data-active] but, now, uses `rw-river-letter-navigation__link--active`.
Finally a tiny change to center vertically the letters.

[RW-59] Style active letter navigation link

---

composer.json
composer.lock
html/modules/custom/reliefweb_rivers/js/advanced-search.js
html/modules/custom/reliefweb_rivers/src/AdvancedSearch.php
html/themes/custom/common_design_subtheme/components/rw-advanced-search/rw-advanced-search.css
html/themes/custom/common_design_subtheme/components/rw-autocomplete/rw-autocomplete.css
html/themes/custom/common_design_subtheme/components/rw-datepicker/rw-datepicker.css
html/themes/custom/common_design_subtheme/components/rw-selection/rw-selection.css

Ticket: RW-65
This fixes the styling of the advanced search, notably by re-introducing the `#main-content` scope so that the advanced search's button styling for example can apply. The base `#main-content form button` was indeed more specific.
This also updates the datepicker library to fix some class prefixing so need to run `composer install`.
Latsly, there is a tiny bug fix in the advanced search logic that I sneaked in there.
What is missing is the 2 columns style for the rivers with the advanced search on the left side of the article list on desktop/tablet, but that's out of the scope of this ticket. Follow-up ticket: RW-69

[RW-65] Fix advanced search styling and other issues

---

html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-description.html.twig
html/themes/custom/common_design_subtheme/components/rw-entity-description/rw-entity-description.css
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-entities/reliefweb-entities-entity-description.html.twig

Ticket: RW-56
This makes a few changes to fix the toggling of the description section:
- Remove the wrapper and (ab)use the `data-cd-replace` attribute to force the addition of the toggler button.
- Update the css rules, notably make sure the description is always shown.
- Add a mutation observer to scroll to the top of the description when `data-cd-hidden` is set to `false`. This emulates what the `data-scroll-to` was doing. This could be replaced if we decide to add this attribute to the `cd-dropdown` upstream.

[RW-56] Fix toggler for description section

---

html/modules/custom/reliefweb_rivers/reliefweb_rivers.module
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--blog-post.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--country.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--disaster.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--job.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--report.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--source.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--training.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-river-article.html.twig

Ticket: RW-70
This adds the missing country river article template for the "Affected Countries" section on disaster pages.
It also adds a header class for the river articles and removes an unused template override.

[RW-70] Affected countries

---

html/modules/custom/reliefweb_dsr/src/Services/DSRClient.php
html/modules/custom/reliefweb_entities/src/Entity/Country.php
html/modules/custom/reliefweb_key_figures/src/Services/KeyFiguresClient.php

Ticket: RW-71
This ensures that there is no DSR or Key Figures item in the Table of contents on country pages when those sections are empty. 
The render array cache, added even when the sections are empty was preventing the corresponding TOC element to be filtered out.
This also uses the proper country status for DSR.

[RW-71] Ensure DSR and Key figures sections are not added when empty

---

html/modules/custom/reliefweb_rivers/src/RiverServiceBase.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-page.html.twig
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/rw-river/rw-river-results.css
html/themes/custom/common_design_subtheme/components/rw-river/rw-river.css

- Add layout rules for advanced search and rivers list, update selectors.
There's still no vertical rhythm and I'm not sure if the generic `rw-river` css file is appropriate for the composition rules. It's a fine place for it in the meantime.
Currently, the Countries and Organizations river pages (maybe Topics also?) don't include the advance search, so the content column spans full width.
But the Organizations page shares the generic `reliefweb-rivers-page.html.twig` template, whereas the Countries page `reliefweb-rivers-country-list.html.twig` has its own template. 
The class `rw-river--river-list` is being used as a selector for the layout CSS. The Country page doesn't have this class so I've used `rw-river-page:not(.rw-river-page--organizations) .rw-river--river-list` to omit …

RW-56 Layout rules for advanced search and rivers list

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-details.html.twig
html/modules/custom/reliefweb_rivers/reliefweb_rivers.module
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--blog-post.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--country.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--disaster.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--job.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--report.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--source.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--training.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river.html.twig
html/modules/custom/reliefweb_utility/reliefweb_utility.module
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-river-article--report.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-river.html.twig

Ticket: RW-106
This is to illustrate a way to add classes to river articles so that different styles can be applied (like headline, maps, appeals).
**Note**: there are already some classes to distinguish between articles with a summary, thumbnail etc., ex: `rw-river-article--with-summary`, which in the card: https://trello.com/c/uYummb5u was referenced as `compact`.
We could extend this article class approach and add a `meta_attributes` variable to the `reliefweb_rivers_river_article` theme and in the `reliefweb-rivers-river-article--report.html.twig` template override, we could add a class for the meta information based on the article class.
For example to add class to always show the entity meta info for the maps section on country page as stacked instead of inline:
```
{% if …
```

[RW-106] Add river article classes

---

html/modules/custom/reliefweb_rivers/reliefweb_rivers.module
html/modules/custom/reliefweb_rivers/reliefweb_rivers.routing.yml
html/modules/custom/reliefweb_rivers/src/Controller/SearchResults.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-search-results.html.twig
html/themes/custom/common_design_subtheme/components/rw-river/rw-river-results.css
html/themes/custom/common_design_subtheme/components/rw-search/rw-search.css
html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-header.html.twig
html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-search.html.twig
html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-site-header.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-search-results.html.twig

Ticket: RW-80
This adds the search to the main header and the search results page (/search/results) which shows a list of resources (ex: reports, countries) matching the search query.
Note: for countries, the full list of matching countries is displayed as the country river is not searchable.

[RW-80] Global search

---

html/modules/custom/reliefweb_rivers/reliefweb_rivers.module
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-page.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river.html.twig

Ticket: RW-31
This adds attributes for the results in the river template and a class variant when in a river with filters in the sidebar to help styling the results: `rw-river-results--with-advanced-serarch`.

[RW-31] Add attributes for the river results

---

html/themes/custom/common_design_subtheme/.stylelintrc.json
html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

`stylelint-no-browser-hacks`  is remove from Drupal 9.2: https://www.drupal.org/project/drupal/issues/3144854

CD-329 Remove stylelint no-browser-hacks plugin

---

html/modules/custom/reliefweb_subscriptions/src/Form/SubscriptionForm.php
html/themes/custom/common_design_subtheme/common_design_subtheme.theme

Ticket: RW-99
The handling of the page title in the CD theme was changed in 5.0.0. This caused to page title on the taxonomy term pages to not be displayed due to some modifications to the functions handling that. This PR fixes this problem.
This also includes a tiny unrelated fix to prevent a PHP error when the database is empty which only happens when resetting the site before testing the migration and clicking the subscriptions tab.
Simply check that the page title is present on some country, disaster and organization pages.

[RW-99] Term page title

---

html/modules/custom/reliefweb_entities/src/DocumentTrait.php
html/themes/custom/common_design_subtheme/components/rw-article/rw-article.css
html/themes/custom/common_design_subtheme/components/rw-article/rw-maps-inforgraphics.css
html/themes/custom/common_design_subtheme/components/rw-blog/rw-blog.css
html/themes/custom/common_design_subtheme/components/rw-organizations/rw-organizations.css
html/themes/custom/common_design_subtheme/components/rw-related-content/rw-related-content.css
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-page.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-river.html.twig

This is an attempt to consolidate the layout for
1. Blog list
2. Organizations list
3. Appeals and Response Plans block on Country page
4. Maps and Infographics block on Country page
5. Related block on Report page
As per this comment https://github.com/UN-OCHA/rwint9-site/pull/60#discussion_r691778092
The difficulty is the lack of shared layout rules these elements have, as explained here: https://github.com/UN-OCHA/rwint9-site/pull/60#issuecomment-903811208

RW-31 column layouts

---

config/core.extension.yml

Ticket: RW-98
Forgot to push the config to enable the taxonomy term preview module.

[RW-98] Enable taxonomy term preview

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php

Ticket: RW-172
This should fix the issue with doksal's mysql which has stricter settings (see [ONLY_FULL_GROUP_BY](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by)).

[RW-172] Fix moderation page query for compatibility with docksal mysql

---

html/modules/custom/reliefweb_moderation/templates/reliefweb-moderation-table.html.twig

Ticket: RW-198
Follow-up of https://github.com/UN-OCHA/rwint9-site/pull/118 to make the classes for the moderation information (status and revision log message) more consistent.

[RW-198] Moderation info classes

---

config/core.entity_form_display.node.report.default.yml

Ticket: RW-127
This simply enables the display of the moderation status (colored border) in the disaster widget for reports.

[RW-127] Add status to disaster widget on report form

---

git-hooks/pre-commit
git-hooks/scripts/pre-commit/lint-common
git-hooks/scripts/pre-commit/lint-js
git-hooks/scripts/pre-commit/lint-php
git-hooks/scripts/pre-commit/lint-phpcs
git-hooks/scripts/pre-commit/lint-sass
html/modules/custom/reliefweb_fields/components/reliefweb-links/reliefweb-links.css
html/modules/custom/reliefweb_fields/components/reliefweb-section-links/reliefweb-section-links.css
html/modules/custom/reliefweb_fields/components/reliefweb-user-posting-rights/reliefweb-user-posting-rights.css
html/modules/custom/reliefweb_rivers/js/advanced-search.js
html/modules/custom/reliefweb_topics/css/reliefweb_topics_community_topics.admin.css
html/modules/custom/reliefweb_topics/js/reliefweb_topics_community_topics.admin.js
html/themes/custom/common_design_subtheme/.stylelintrc.json

Ticket: RW-213
Improve pre-commit linting scripts, add JS one and allow passing a directory to check instead of only linting only staged files.
Example: `./git-hooks/pre-commit -d ./html/modules/custom`
Also ran the linting scripts against the current code base and fixed a few css/js warnings/errors.
**Note** for the JS and CSS linting to run, `npm install` must have been run inside `html/themes/custom/common_design_subtheme/`.

[RW-213] Linting

---

html/themes/custom/common_design_subtheme/components/rw-country-slug/rw-country-slug.css
html/themes/custom/common_design_subtheme/components/rw-pager/rw-pager.css
html/themes/custom/common_design_subtheme/components/rw-revisions/rw-revisions.css
html/themes/custom/common_design_subtheme/templates/navigation/pager.html.twig

Based on recent QA and discussion
-  RW-100 style checked/uncheck revision like D7
- Hide country slug in all sections on Country pages
- Change pagination heading from h4 to h3
- On pages with `rw-river-page--with-advanced-search` change pagination width to span full width of container, despite its parent section width being restricted
**To Test:**
Pagination on `/organizations` should display as usual
On pages like `/updates` pagination should span full width and remain centered from 768px upwards

RW-31 more frontend QA

---

html/modules/custom/reliefweb_entities/src/Entity/Book.php

Ticket: RW-253
This fixes the logic to determine the active link in the book navigation:
Simply check that the highlighted entry in the book navigation corresponds to the current page.

[RW-253] Fix active link in book navigation

---

html/modules/custom/reliefweb_entities/src/SectionedContentTrait.php

Ticket: RW-252
This prevents the display of sections on country/disaster/topic etc. pages when their content is basically empty (ex: /topic/humanitarian-financing overview is just 2 blank lines so it shouldn't be displayed).

[RW-252] Prevent display of text section with 'empty' content

---

html/themes/custom/common_design_subtheme/components/rw-article/rw-article.css
html/themes/custom/common_design_subtheme/components/rw-blog/rw-blog.css
html/themes/custom/common_design_subtheme/components/rw-homepage/rw-homepage.css
html/themes/custom/common_design_subtheme/components/rw-river-letter-navigation/rw-river-letter-navigation.css
html/themes/custom/common_design_subtheme/components/rw-toc/rw-toc.css

1. Fix flexbox issue with TOC when there is only one item
2. IE11 fixes for cd-dropdown
3. Adjust selectors to match changes in `rw-article` #171 so override rules apply as intended

RW-31 More QA

---

config/theme_switcher.rule.request_path.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/rw-user-posting-right/rw-user-posting-right.css
html/themes/custom/common_design_subtheme/components/rw-user-posting-rights/rw-user-posting-rights.css
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_moderation/reliefweb-moderation-user-posting-right.html.twig

RW-257
- split libraries for user posting right/s
- add as dependency where relevant
I've checked 
1. `node/3758093/edit` (Training user information)
2. `taxonomy/term/2007/user-posting-rights` Organization user posting rights
3. `taxonomy/term/2007/edit#edit-revision-information` or `taxonomy/term/2007/user-posting-rights` Organization revisions user posting rights
4. `moderation/content/training`
I don't see the class `rw-user-posting-right` applied to the revision history spans. @orakili Can you take a look? And also let me know if there are other places this component appears that I neglected to check.

RW-257 User posting right/s

---

html/themes/custom/common_design_subtheme/components/rw-report/rw-report.css
html/themes/custom/common_design_subtheme/templates/content/node--report--full.html.twig

- Update selectors from D7 to reflect BEM naming for D9 including `rw-attachment--` as class variants
- Add wrapper div inside existing `.rw-article__content` so the content body and the `.rw-attachment--report` respects their float rules.
- TEMP commented-out markup directly into Report node template override to test

RW-25 Report attachments

---

html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php

Ticket: RW-262
This uses a different state variable for the status when saving a job or training with a potential new source as the jobs team seems to prefer to have the posts saved as "on-hold" while the training team seems to prefer to have them saved as "pending".

[RW-262] Potential new source status

---

html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
html/themes/custom/common_design_subtheme/templates/form/text-format-wrapper.html.twig

Template override to add class `description` to field description div to use generic form styling and thus remove specific rule that conflicts with the main text areas.

RW-263 Full text description remove italics

---

config/field.field.node.report.field_origin.yml
config/field.storage.node.field_origin.yml

Ticket: RW-209
This changes the "field_origin" field type to `list(integer)` to be compatible with the field in D7 so that the data is properly migrated. The previous field type `list(text)` was selected by mistake.

[RW-209] Fix report field_origin

---

git-hooks/scripts/pre-commit/lint-sass
html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

Ticket: RW-264
This updates the subtheme node dependencies by copying the package.json and package-lock.json from the base theme (4.0.0 --> 5.0.1).
This also moves `eslint` to the "dependencies" rather than the "devDependencies" so JS can be linted without having to install heavier dependencies like svg-sprite and puppeteer.
Finally, this hopefully fixes the compatibility of the css pre-commit linting with docksal (but that my require stylelint 14.x to work properly).

[RW-264] Update package.json

---

html/modules/custom/reliefweb_entities/src/Plugin/Validation/Constraint/DateEndAfterStartConstraintValidator.php
html/modules/custom/reliefweb_entities/src/Plugin/Validation/Constraint/DateNotInPastConstraintValidator.php
html/modules/custom/reliefweb_entities/src/Plugin/Validation/Constraint/EmptyIfOtherFieldEmptyConstraintValidator.php
html/modules/custom/reliefweb_entities/src/Plugin/Validation/Constraint/MaxNumberOfValuesConstraintValidator.php
html/modules/custom/reliefweb_entities/src/Plugin/Validation/Constraint/TextLengthWithinRangeConstraintValidator.php

Ticket: RW-272
This fixes the field validation constraints that were causing exceptions when editing the field config for example.
Before checkout the RW-272 branch, go to `/admin/structure/types/manage/job/fields/node.job.body` and click "save settings", there should be an exception.
Checkout the RW-272 branch, clear cache and go to `/admin/structure/types/manage/job/fields/node.job.body`. There should be no issue when saving the settings.
Create a job `/node/add/job`, fill the mandatory field but put only a tiny text in the "job description". You should get a "The Job description number of characters must be with 400 and 50000" error message confirming the validation works.

[RW-272] Fix validation constraints

---

docker/etc/nginx/custom/01_legacy_file_redirections.conf

Ticket: RW-288
This makes the legacy file routes more explicit so that we let the default apps/drupal/drupal.conf handle serving the files. this notably prevents issues with the aggregated css/js.

[RW-288] Explicit the routes to redirect legacy files

---

composer.patches.json

Split out from https://github.com/UN-OCHA/rwint9-site/pull/206 - this adds the patch suggested in https://www.drupal.org/project/migrate_tools/issues/3256236.

[RW-294] patch migrate_tools placeholder error

---

html/modules/custom/reliefweb_guidelines/src/Services/GuidelineModeration.php
html/modules/custom/reliefweb_moderation/reliefweb_moderation.module
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/Services/JobModeration.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/modules/custom/reliefweb_moderation/src/Services/TrainingModeration.php
html/modules/custom/reliefweb_utility/src/Helpers/UserHelper.php

Ticket: RW-336
It turns out that `AccessResultNeutral` [is not neutral](https://www.drupal.org/project/drupal/issues/2991698) when used in a route access check, so this ticket rewrites a bit the entity access in the moderation module to work around that inconsistency.

[RW-336] Fix entity access

---

html/themes/custom/common_design_subtheme/components/rw-guidelines/rw-guidelines.css

RW-343 This looks after the display with the WYSIWYG only, and keeps the rule from RW-322 which does the same thing for the autocomplete widget.

RW-343 add clearfix rule to clear preceding floated element

---

config/field.field.taxonomy_term.disaster.field_profile.yml
html/modules/custom/reliefweb_entities/src/Entity/Country.php
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebEntityReferenceSelect.php
html/modules/custom/reliefweb_form/js/widget.autocomplete.js
html/modules/custom/reliefweb_guidelines/src/Commands/ReliefWebGuidelinesCommands.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/Services/CountryModeration.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/modules/custom/reliefweb_user_posts/src/Services/UserPostsService.php

- RW-285/RW-348: fix various issues with the OCHA product field on reports
- RW-349: make show profile selected by default on disaster form
- RW-350: assign IDs for guideline path aliases that don't conflict with the other migrated url aliases
- RW-351: fix moderation status data attribute on forms
- RW-352: remove leftover of moderation_state to fix issues with status when saving a job/training with a potential new source
- RW-353: make the "archived" status unselected by default on the report moderation page
- RW-354: remove "draft" status for countries
- RW-355: remove "save and go to list" button on country, disaster and source forms

Various fixes

---

config/core.entity_form_display.node.announcement.default.yml
config/core.entity_form_display.node.blog_post.default.yml
config/core.entity_form_display.node.book.default.yml
config/core.entity_form_display.node.report.default.yml
config/core.entity_form_display.node.topic.default.yml
config/core.entity_form_display.taxonomy_term.country.default.yml
config/core.entity_form_display.taxonomy_term.country.profile.yml
config/core.entity_form_display.taxonomy_term.disaster.default.yml
config/core.entity_form_display.taxonomy_term.disaster.profile.yml
config/core.entity_form_display.taxonomy_term.source.default.yml
config/field.field.node.announcement.field_link.yml
config/user.role.editor.yml
config/user.role.user_manager.yml
config/user.role.webmaster.yml
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/src/Entity/BlogPost.php
html/modules/custom/reliefweb_entities/src/Entity/Job.php
html/modules/custom/reliefweb_entities/src/Entity/Training.php
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_entities/src/OpportunityDocumentTrait.php
html/modules/custom/reliefweb_entities/src/Services/AnnouncementFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/CountryFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/DisasterFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/SourceFormAlter.php
html/modules/custom/reliefweb_form/reliefweb_form.module
html/modules/custom/reliefweb_users/reliefweb_users.permissions.yml
html/modules/custom/reliefweb_utility/src/Plugin/Filter/Markdown.php
html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-footer.html.twig

- RW-123: Add permission to view the reliefweb admin menu
- RW-369: Add entity label validation for cloned entities
- RW-223: Adjust the announcement field descriptions and settings
- RW-224: Consolidate text format help, styling and add markdown reference to the help page
- RW-379: Update the source(s) moderation status to `active` when publishing a job/training
- RW-380: Update block post date when published
- RW-382: Update job/training status to `refused` when publishing if one of the source(s) is blocked.
- RW-383: Update job/training date when published for the first time

Various fixes - part 4

---

html/themes/custom/common_design_subtheme/common_design_subtheme.theme
html/themes/custom/common_design_subtheme/src/FormElementOptional.php

Ticket: RW-467
This PR delays the addition of the "optional" mark so that other places using the form element title (ex: to set an error message) see the original one.
Due to the way drupal builds the form elements we need to pass around the optional information before we can finally alter the title:
1. Process function to add an `after build` callback to the relevant form elements
2. After build callback to add the `pre render` callbacks to add the optional mark
3. Pre render callback to add the "optional" mark
Create a training, for example, and leave the "registration deadline" empty. Without this PR, the error message at the top should show "Registration deadline - optional". With the PR, the message should show "Registration deadline" only.
Other optional fields like "Theme" should …

[RW-467] Only add optional mark before rendering form elements

---

composer.lock
composer.patches.json
config/field.field.guideline.field_guideline.field_links.yml
html/modules/custom/reliefweb_docstore/src/Plugin/Field/FieldType/ReliefWebFile.php
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_fields/components/reliefweb-links/reliefweb-links.js
html/modules/custom/reliefweb_fields/components/reliefweb-section-links/reliefweb-section-links.js
html/modules/custom/reliefweb_fields/components/reliefweb-user-posting-rights/reliefweb-user-posting-rights.js
html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebLinks.php
html/modules/custom/reliefweb_form/js/widget.datepicker.js
html/modules/custom/reliefweb_guidelines/components/reliefweb-guidelines/reliefweb-guidelines.css
html/modules/custom/reliefweb_guidelines/components/reliefweb-guidelines/reliefweb-guidelines.js
html/modules/custom/reliefweb_guidelines/src/Controller/GuidelineSinglePageController.php
html/modules/custom/reliefweb_guidelines/src/Entity/Guideline.php
html/modules/custom/reliefweb_guidelines/src/Entity/GuidelineList.php
html/modules/custom/reliefweb_guidelines/src/Services/GuidelineModeration.php
html/themes/custom/common_design_subtheme/templates/content/taxonomy-term--country--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/taxonomy-term--disaster--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/taxonomy-term--source--full.html.twig
html/themes/custom/common_design_subtheme/templates/field/field--guideline--field-links.html.twig
html/themes/custom/common_design_subtheme/templates/navigation/menu--help.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/guideline/guideline--field-guideline--full.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/guideline/guideline--guideline-list--full.html.twig

- RW-443: Fix caching of guidelines page
- RW-444: Ensure the revision log message field is empty when editing content
- RW-445: Make exit link redirect to referrer on guidelines page
- RW-446: Change links on guideline moderation page
- RW-447: Add link to guideline list on guideline page 
- RW-448: Open guidelines in new tab
- RW-452: Show reference links at bottom of guidelines
- RW-472: Set date of datepicker when opening it
- RW-476: Add revision information at bottom of country, disaster and source pages
- RW-477: Fix issue with display of error message on country/disaster profile form
- RW-478: Prevent PHP warning when image file is missing
- RW-479: Restore inline_entity_form patch
- RW-480: Show guidelines on guideline list page
- RW-481: Limit width of images on guidelines page

Various fixes - part 21

---

composer.json
composer.lock
html/themes/custom/common_design_subtheme/common_design_subtheme.theme
html/themes/custom/common_design_subtheme/templates/cd/cd-icons/cd-icons.html.twig
html/themes/custom/common_design_subtheme/templates/layout/html.html.twig

- Upgrade base theme to v7 https://github.com/UN-OCHA/common_design/releases/tag/v7.0.0
- Removes the SVG icon sprite from being attached in the sub theme preprocess, and instead uses a template override
There should be visual changes, and the social media icons should continue to display in the footer.

RW-438 update base theme and SVG sprite icon partial

---

config/field.field.node.report.field_origin_notes.yml

I also updated the link in the [guidelines](https://reliefweb.int/admin/structure/guideline/21/edit) (from `guideline/AS0L5YBd35` to `guidelines#AS0L5YBd` without the 35 at the end). I've now seen [there's already a fix](https://github.com/UN-OCHA/rwint9-site/pull/330) that means I didn't need to change the slash for a #, (or indeed make the change at all) but it's not deployed yet so I can change that back afterwards.
I considered mentioning the notify box here while editors get used to 'the new way', but decided it's better not to.

[RE-537] update help text for origin url field

---

docker/etc/nginx/custom/01_attachment_redirections.conf

Disable nginx rules related to the docstore as it is not used to avoid upstream not found issues when there is no connected docstore instance.

[RW-554] Disable nginx rules related to the docstore

---

html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
html/themes/custom/common_design_subtheme/components/rw-user/rw-user.css

I moved the unsubscribe form rules from `rw-user` component and added them to `rw-form` which is part of the global library. The first attempt #353 didn't work because the library isn't loaded onto that page and since I cannot view this page locally, using the global library seems like the most straight-forward.

RW-573 Unsubscribe form styles in global library

---

docker/etc/nginx/custom/lua/01_legacy_attachment_redirections.lua
html/modules/custom/reliefweb_files/drush.services.yml
html/modules/custom/reliefweb_files/src/Commands/ReliefWebFilesCommands.php

Refs: OPS-8377
This contains 2 parts:
1. An update of the legacy attachment redirection lua script to check for symlinks similar to what is done for some previews
2. A drush command that can be used to generate redirection symlinks

[OPS-8377] legacy redirection symlinks

---

html/modules/custom/reliefweb_analytics/reliefweb_analytics.module
html/modules/custom/reliefweb_analytics/src/Command/ReliefwebMostReadCommand.php
html/modules/custom/reliefweb_entities/src/SectionedContentTrait.php
html/modules/custom/reliefweb_homepage/src/Controller/Homepage.php

Refs: RW-23
Follow-up of https://github.com/UN-OCHA/rwint9-site/pull/376 that adjusts and fixes a few things.
The 2 main changes are:
The addition of the the "contains" match type to the disaster/country filters so that reports tagged with multiple terms are included. This was the reason why the results were different from the single request command.
With that match type, the results from the individual requests and the single large requests are the same so there is actually no need for the individual ones which makes things dramatically faster.
The second main change is the use of the `url_alias` property for the RW API query so that we don't have to do path alias lookups. This, notably makes testing locally much simpler (see below).
The `property id` is retrieved via `Settings:get` …

[RW-23] Most read adjustments

---

html/modules/custom/reliefweb_form/js/drupal.states.js

Refs: RW-608
This fixes an issue where the "optional" mark is not removed for fields that become required via drupal.states.
Ex: the headline title and summary fields on the report form when the headline checkbox is checked.
**Test**
1. Go to the `/node/add/report` form
2. Check the `headline` checkbox -> this should remove the "optional" mark on the headline title and summary fields and add it back when unchecking

[RW-608] Optional mark

---

html/modules/custom/reliefweb_entities/reliefweb_entities.install
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/reliefweb_entities.post_update.php

Refs: RW-594
Sister PR of: https://github.com/UN-OCHA/rwint-api-indexer/pull/39 and https://github.com/UN-OCHA/rwint-api/pull/96
Taxonomy terms don't have a "created" field: https://www.drupal.org/project/drupal/issues/2869432
So this adds a "created" field to taxonomy terms and populate it with the oldest revision timestamp or the event date for disasters for compatibility with what is currently returned by the RW API.
**Note 1**: once https://github.com/UN-OCHA/rwint-api-indexer/pull/39 is merged and a new release created, we'll have to update the version in the rwint9-site repo.
**Note 2**: once deployed, we'll need to do a full re-indexing of the countries, disasters and sources with a new index tag to take into account the updated ES schemas.

[RW-594] Add a created field to taxonomy terms

---

composer.json
composer.lock

Refs: RW-594
Follow up of https://github.com/UN-OCHA/rwint9-site/pull/406 to bump the api-indexer to the version that index the date fields for countries, disasters and sources.

[RW-594] Bump api indexer version

---

html/modules/custom/reliefweb_api/drush.services.yml
html/modules/custom/reliefweb_api/reliefweb_api.module
html/modules/custom/reliefweb_api/src/Commands/ReliefWebApiCommands.php
html/modules/custom/reliefweb_entities/src/BundleTaxonomyTermStorage.php

Refs: RW-588
Includes a new entity_before_save hook, which was added reluctantly. I had
trouble getting the unchanged content of the entity in hook_entity_update or
hook_entity_after_save.

feat: queue filtered re-indexing for processing later

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php

Refs: RW-615
Date fields store the value in the `Y-m-d` format so we need to convert them to timestamps to compare with the filter values.
Affected fields:
- field_job_closing_date
- field_registration_deadline
- field_disaster_date
The `field_training_date` would be affected to but there is no filter on it (not requested).

[RW-615] Fix moderation backend date filter

---

html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/js/cd-ajax-disable-submit-buttons.js

Refs: RW-621
This adds a script added when `ajax.js` is added to a form for example, that disables the form submit buttons while an ajax request is being performed (ex: file/image upload) to prevent mistakes.
Note: this could be added to the CD's subtheme with the following commented out in the `common_design_subtheme.info.yml`
```yaml
core/drupal.ajax:
- common_design_subtheme/cd-ajax-disable-submit-buttons
```
so that devs could enable this behavior if interested.
1. In your browser of choice, if the option is available, set some throttling so that you can see the effect (ex: Firefox dev tools > Network tab > Throttling -> Regular 3G)
2. Go to the `report` form go the "Files" section, upload a large enough file (ex: 500Kb if throttling is enabled)
3. While the file is being uploaded, go …

[RW-621] Disable form submission during ajax requests

---

config/user.role.webmaster.yml
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/reliefweb_entities.services.yml
html/modules/custom/reliefweb_entities/src/Entity/TaxonomyTermBase.php
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_entities/src/Services/TaxonomyTermFormAlter.php
html/themes/custom/common_design_subtheme/templates/block/block--local-actions-block.html.twig

Refs: RW-622
This PR adds a missing permission for the Webmaster role to view the list of vocabularies at  `/admin/structure/taxonomy` (Admin menu > Manage > Taxonomy), so that they can notably change the term descriptions used in the popup in the job/training form for example. (This just restores the behavior from RW7.)
It also gives some love to the taxonomy forms to ease the edition of the terms:
- Disallow re-ordering the vocabularies and terms to prevent mistakes (like setting a term as a child of another term which is not something currently allowed on RW)
- Restrict the description text format to "plain text" (like on RW7)
- Show the revision history
1. Log in with an Editor account, check that you cannot access `/admin/structure/taxonomy` and `/taxonomy/term/12570/edit` for …

[RW-622] Editing taxonomy terms

---

composer.lock
html/modules/custom/reliefweb_guidelines/src/Controller/GuidelineSinglePageController.php
html/modules/custom/reliefweb_guidelines/src/Form/GuidelineForm.php
html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/common_design_subtheme/components/rw-guidelines/rw-guidelines--preview.css
html/themes/custom/common_design_subtheme/components/rw-preview/rw-preview.css
html/themes/custom/common_design_subtheme/templates/form/form--guideline-preview-form-select.html.twig

Reds: RW-624
This PR updates the GuidelineForm class override to handle the preview added in https://www.drupal.org/project/guidelines/releases/1.0.4 and style the preview to be consistent with the node and term preview on RW.
Run `composer install` after checking out the branch to update the `guidelines` module.
1. Open a guideline page
2. Edit it, make some changes
3. Click Preview, check that the preview looks like the guideline page from (1) but with the changes
4. Click a link and check that there is a confirmation popup
5. Click "back to content editing"
6. Check that changes from (2) are still present 
7. Save and check that the changes were applied

[RW-624] Guideline preview

---

html/modules/custom/reliefweb_moderation/src/Helpers/UserPostingRightsHelper.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php

Ref: RW-626
There were actually 2 issues:
- Invalid query for the filter resulting in a PHP error
- Invalid logic to get the author posting rights in case there is no record for its account for a source (should be unverified).

[RW-626] Fix posting rights filter on moderation backend

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_utility/src/Helpers/EntityHelper.php
html/themes/custom/common_design_subtheme/templates/layout/page--403.html.twig

Refs: RW-513
This adds back the display of a message for node pages when access is denied to indicate the node is no longer available.
This takes the assumption that people getting a 403 is because the page previously accessible like a published job but is no longer available because the job has expired. The displayed message makes the 403 page a bit more user friendly:
1. Log in and find or create a non published (ex: expired) job, training or report, copy the URL
2. Open an incognito tab for example and paste the URL and confirm that the message "The XXX blabla is not available anymore" appears.
3. View another page anonymously like`/moderation/content/report` and confirm there no "not available ..." message on the 403 page.

[RW-513] Message for 403 on node page

---

config/reliefweb_rivers.settings.yml
html/modules/custom/reliefweb_api/src/Services/ReliefWebApiClient.php
html/modules/custom/reliefweb_rivers/config/install/reliefweb_rivers.settings.yml
html/modules/custom/reliefweb_rivers/reliefweb_rivers.module
html/modules/custom/reliefweb_rivers/reliefweb_rivers.routing.yml
html/modules/custom/reliefweb_rivers/src/Controller/SearchConverter.php
html/modules/custom/reliefweb_rivers/src/Form/SearchConverterForm.php
html/modules/custom/reliefweb_rivers/src/RiverServiceBase.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-search-converter.html.twig
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.theme
html/themes/custom/common_design_subtheme/components/rw-search-converter/rw-search-converter.css
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_rivers/reliefweb-rivers-search-converter.html.twig

Refs: RW-389
At the bottom of the rivers like https://reliefweb.int/updates there is an `API` link that redirects to the RW search converter that converts the river URL to an API query which can be used to get data similar to what is displayed in the river.
This search converter is currently a github page: https://reliefweb.github.io/search-converter.
This PR adds a search converter page directly on the RW site so that we don't have to duplicate the conversion logic which is already used for the rivers: `/search/converter` which is accessible via the API link at the bottom of the rivers.
Checkout this branch and run `drush cr` and `drush cim`.
1. Go the https://reliefweb.int/updates, select some filters and add a full text search query
2. Click the `API` link at the bottom to go the …

[RW-389] Add search converter to RW

---

html/modules/custom/reliefweb_form/reliefweb_form.module
html/modules/custom/reliefweb_form/src/ParamConverter/NodePreviewConverter.php
html/modules/custom/reliefweb_form/src/ReliefWebFormServiceProvider.php

Refs: RW-564
This adds a workaround to be able to view the images when previewing a node with fields using an inline entity form for those image (ex: report image).
1. Create a report, add an image (under the Files section), fill the mandatory fields
2. Click preview and confirm you can see the image
3. Go back to the form and save
4. Edit the report, edit the image (change the uploaded image for example), click "update image"
5. Click preview and confirm you can see the new image

[RW-564] view attached images when previewing node

---

docker/etc/nginx/custom/lua/01_legacy_attachment_redirections.lua

Refs: RW-632
Found some occasional nginx 500 in the logs for legacy attachment URLs. It turned out those URLs contained bytes like `\x1` that are considered unsafe when redirecting.
This PR makes sure the file name is encoded before redirecting.
1. Before switching to this PR's branch, check this URL: `/sites/reliefweb.int/files/resources/ED1EF744FE93A788C%1F1257428003110CB-gvtSweden_feb2006.pdf`, it should return a 500
2. Checkout this PR's branch, **restart the container** and check the same URL, it should return a 404

[RW-632] Encode file name when doing legacy redirections

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_utility/src/Helpers/MediaHelper.php

Refs: RW-629
This ensures the attached media images and their files are deleted when deleting a report or announcement.
1. Create a node, attach an image (under Files section), save
2. Run `drush sql-query "SELECT * FROM file_managed ORDER BY fid DESC LIMIT 1"` and check the status of  the file is `1`. Note the `fid` and replace `FID` with it in the queries in (4) and (6) below.
3. Delete the node
4. Run `drush sql-query "SELECT * FROM file_managed WHERE fid = FID"` and check the status of  the file is `0`.
5. Run `drush cron`
6.  Run `drush sql-query "SELECT * FROM file_managed WHERE fid = FID"` and check that there is no record anymore.

[RW-629] ensure media and files are deleted when deleting a node

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module

Refs: RW-633
This fixes an issue where Drupal returns a 500 instead of a 403 when selecting a source in a job/training form as a non-editor.
Note: code is best reviewed with `?w=1` as all this does is wrapping the code in a try/catch.
Before checking out this branch:
1. Go to `/node/add/job` as non Editor
2. Open your browser inspector's network tab
3. Select a source (ex: OCHA) and check that there is a call to `/admin/reliefweb_form/node_form/source_attention_messages/job` that returns a 500
Checkout the branch, do the same steps as above but this time, the return status should be 403 (expected as the user doesn't have the right to access the source_attention_messages endpoint).

[RW-633] skip 403 preprocessing if the router throws an exception

---

html/themes/custom/common_design_subtheme/common_design_subtheme.theme

Refs: RW-636
This adds `<link>` elements to the head to preload the SVG sprites and logos and the google font stylesheet to reduce the time to the first contentful paint.
**Before**
**After**

[RW-636] Preload SVG and font stylesheet

---

html/modules/custom/reliefweb_moderation/src/Services/TopicModeration.php

Refs: RW-654
This simply enables the "archive" status for topics.
1. Select a published topic, check that it can be accessed as anonymous
2. Log in as an Editor
3. Edit the topic, check that there is an "Archive" button, click on it
4. Check that the topic status is "archived" and that the topic is not accessible anonymously anymore5. 
5. Check that, as an Editor the topic is accessible and editable
6. Log in as a normal user and check that the topic is not accessible

[RW-654] Allow topics to be archived

---

html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-search.html.twig

This PR replaces some D7 syntax with D9 twig translation for the Search section heading
Refs: RW-640

RW-640 Global Search section heading

---

docker/etc/nginx/custom/lua/01_legacy_attachment_redirections.lua
docker/etc/nginx/custom/lua/01_legacy_preview_derivative_redirections.lua
docker/etc/nginx/custom/lua/01_legacy_preview_redirections.lua

Since io.popen() spawns a shell, we do not want to pass it any special
characters that would end up with a shell exploit.
Refs: OPS-8576

fix: Strip quotes, backticks and dollars from the string we're looking up.

---

html/modules/custom/reliefweb_moderation/src/Services/SourceModeration.php

Refs: RW-658
This updates the `SourceModeration` service to call the parent `entityPresave` to ensure the term `status` field is properly updated when the moderation status changes.
1. Find a source with a "status" of 0: `SELECT tid FROM taxonomy_term_field_data WHERE status = 0 LIMIT 1`
2. Edit the source, save it as `active`
3. Check that the status is still `0`: `SELECT status FROM taxonomy_term_field_data WHERE tid = TID` (replace `TID`)
1. Find a source with a "status" of 0: `SELECT tid FROM taxonomy_term_field_data WHERE status = 0 LIMIT 1`
2. Edit the source, save it as `active`
3. Check that the status is now `1`: `SELECT status FROM taxonomy_term_field_data WHERE tid = TID` (replace `TID`)
4. Edit the source, …

[RW-658] Ensure source status field is properly updated

---

config/migrate_plus.migration.reliefweb_node_revision__job.yml
config/migrate_plus.migration.reliefweb_node_revision__report.yml
config/migrate_plus.migration.reliefweb_node_revision__training.yml
html/modules/custom/reliefweb_migrate/config/install/migrate_plus.migration.reliefweb_node_revision__job.yml
html/modules/custom/reliefweb_migrate/config/install/migrate_plus.migration.reliefweb_node_revision__report.yml
html/modules/custom/reliefweb_migrate/config/install/migrate_plus.migration.reliefweb_node_revision__training.yml
html/modules/custom/reliefweb_migrate/src/Commands/ReliefWebMigrateCommands.php

Refs: RW-656
This adds a drush command `rw-migrate:migrate-career-categories-revisions` to migrate the career categories field revisions for jobs and training.
Note: this is a copy of the command for the migration of the report content format field revisions which was run on prod some weeks ago.
**Before running command**
Check some of the jobs/training below (they may not all be present depending on the freshness of the DB):
- 3815248
- 3815474
- 3827433
- 3829452
- 3829454
- 3830059
- 3834284
- 3834655
- 3837945
- 3839887
- 3839888
- 3839889
- 3839890
- 3839892
- 3839894
- 3841988
The `professional function` for training or the `career categories` field in the revision history should be missing from the oldest revisions (before May 15).
**After running the command**
Check the same node …

[RW-656] Migrate career categories field revisions

---

composer.json
composer.lock
html/modules/custom/reliefweb_rivers/src/Services/SourceRiver.php

Refs: RW-659
This uses the collation field introduced in https://github.com/UN-OCHA/rwint-api-indexer/pull/42 to sort the organizations alphabetically.
**Important**
This requires the update of the API indexer in https://github.com/UN-OCHA/rwint-api-indexer/pull/42 and the corresponding update of the API: https://github.com/UN-OCHA/rwint-api/pull/102
This uses the temporary `v2.5.0-alpha` tag of the API indexer for the purpose of testing and that will need to be changed to v2.5.0 when available.
**Prerequisites**
1. Install the `analysis-icu` plugin in the elasticsearch container: `docker exec -it rwint9-elasticsearch bin/elasticsearch-plugin install analysis-icu`
2. Update the local API with https://github.com/UN-OCHA/rwint-api/pull/102
1. Go to your …

[RW-659] Use collation field to sort organizations

---

docker/etc/nginx/custom/01_attachment_redirections.conf

This does not affect the file extension in the content-disposition header, which is the same case as the original upload.
Refs: OPS-8473

fix: Force the file extension to lowercase for file access, as that is how we store it.

---

config/google_tag.settings.yml
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-image.html.twig
html/modules/custom/reliefweb_files/reliefweb_files.module
html/modules/custom/reliefweb_files/templates/reliefweb-file-list--interactive.html.twig
html/modules/custom/reliefweb_files/templates/reliefweb-file-list.html.twig
html/modules/custom/reliefweb_homepage/templates/reliefweb-homepage-announcement.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--report.html.twig
html/themes/custom/common_design_subtheme/common_design_subtheme.theme
html/themes/custom/common_design_subtheme/components/rw-cd-header-footer/cd-footer.css
html/themes/custom/common_design_subtheme/img/logos/ocha-logo-sprite.svg
html/themes/custom/common_design_subtheme/templates/content/node--blog_post--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/node--report--full.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_homepage/reliefweb-homepage.html.twig

Refs: RW-667
This adds a series of performance improvements:
- RW-660: add loading attribute for river thumbnails
- RW-661:  load the announcement image and first headline image eagerly on the homepage
- RW-662, RW-663:  load the report image or first attachment preview eagerly
- RW-664: load blog image eagerly
- RW-665: inline GTM loading snippet
- RW-666: preload mobile logo
- RW-668: use OCHA logo sprite for OCHA logo in footer
Run some performance profiling tools (with throttling) on your local site (ex: lighthouse), and record the results for:
- (1) homepage, 
- (2) report with an image, 
- (3) report with an attachment with a preview but no image
- (4) report with an image and an attachment
- (5) blog post with an image
**After checking out this …

[RW-667] Performance improvements

---

.dockerignore
assets/robots.txt.append
composer.json
docker/Dockerfile

Refs: RW-635
This simply appends back (was in D7) the sitemap location to the robots.txt
2. Build the image with make and rebuild container
3. Check /robots.txt to confirm there is "Sitemap: https://reliefweb.int/sitemap.xml" at the end

[RW-635] Add sitemap entry to robots.txt

---

html/modules/custom/reliefweb_disaster_map/js/disaster-map.js
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--disaster.html.twig
html/themes/custom/common_design_subtheme/components/rw-disaster-map/rw-disaster-map.css
html/themes/custom/common_design_subtheme/components/rw-disasters/rw-disasters.css

Refs: RW-672, RW-671, RW-646
This improves the accessibility of the disaster map by highlighting the disaster markers on the map and showing the popup when navigating by keyboard.
There is also a tiny fix for the icons of the related disasters where the use of the wrong css variable resulted in a wrong position.
1. Checkout this branch, clear the cache
2. Open the /disasters page and use `tab` to navigate until reaching the map
3. Check that this highlight markers on the map and shows the popup.
4. Check that related disasters can also be reached with `tab`
5. Check that pressing `escape` closes the popup and than `tab` jumps to the next disaster
Re. (4), here's a screenshot showing related disasters (you may need to tab through several disasters to find one with related disasters):

[RW-672] Disaster map accessibility

---

config/google_tag.container.default.yml

Refs: RW-673
This remove the setting that preventing the GTM loading script from being injected in 403/404 pages.
1. Checkout the branch and import the config (`drush cim`)
2. Type a random non existing URL (404) and check that the inline GTM loading script is there
3. Open closed job for example (403) and check that the GTM loading script is there

[RW-673] Enable GTM on 403/404

---

html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--topic.html.twig

Refs: RW-649
This removes the empty "lang" attribute from the topics river article template because there is currently no way to specify the language of a topic (no language field). We cannot default to English but some topics are mostly in another language like https://reliefweb.int/topics/am-rica-latina-y-el-caribe for example.
1. Go to /topics, inspect the summary of a topic and check that there is an empty "lang" attribute for the content
1. Clear the cache
2. Go to /topics and check that there si no "lang" attribute anymore

[RW-649] Remove the lang attribute for topics

---

html/modules/custom/reliefweb_entities/src/Services/JobFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/TrainingFormAlter.php

Refs: RW-634
This disables trying to fetch the attention message when selecting a source in the job or training form when the current is not an editor. Currently this returns unnecessary 403s.
1. Log in as a normal user (non editor)
2. Go the /node/add/training to create a training
3. Open the network tab in your browser's dev tools
4. Select "UN Women" and check that there is a request to `admin/reliefweb_form/node_form/source_attention_messages/training` that returns a 403 and that no attention message appears 
5. Login in as an editor, repeat the steps below and check that the request above returns a 200 and that the attention message appears in the form6. 
Repeat the steps below and check that at (4) there is no …

[RW-634] do not attempt to fetch source attention message when not an editor

---

html/modules/custom/reliefweb_files/templates/reliefweb-file-list--interactive.html.twig
html/modules/custom/reliefweb_files/templates/reliefweb-file-list.html.twig

Refs: RW-678
This fixes an issue with some reports with attachments without a proper preview.

[RW-678] prevent twig exception when a file preview doesn't have attributes

---

html/modules/custom/reliefweb_subscriptions/src/ReliefwebSubscriptionsMailer.php
html/modules/custom/reliefweb_utility/src/Helpers/HtmlSummarizer.php
html/modules/custom/reliefweb_utility/tests/src/Unit/HtmlSummarizerTest.php

Refs: RW-89
This updates the reliefweb_utility's `HtmlSummarizer` (split logic into 3 methods) and uses it for the subscriptions to reduce duplicate code.
1. Set the `reliefweb_api.settings` `api_url` to `https://api.reliefweb.int/v1` to be sure to have fresh content
2. Log in as an admin
3. Go to `/admin/subscriptions/preview/headlines` (or appeals for example to find something with content), click preview
4. Inspect the preview email and take note of the "preheader" div element's content.
5. Take note of the summary of some articles in the preview
6. Go to `/admin/subscriptions/preview/disaster`, inspect and take note of the `preheader`
1. Repeat steps from above
2. Compare the preheaders and summaries with the ones …

[RW-89] Use utility summarizer for subscription emails

---

html/modules/custom/reliefweb_bookmarks/reliefweb_bookmarks.module
html/modules/custom/reliefweb_bookmarks/src/Controller/UserBookmarksController.php
html/modules/custom/reliefweb_bookmarks/templates/reliefweb-bookmarks.html.twig
html/themes/custom/common_design_subtheme/components/rw-user/rw-user-bookmarks.css
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_bookmarks/reliefweb-bookmarks.html.twig

Refs: RW-221
This fixes a couple of issues with the bookmarks (see first 2 commits) and add some tab navigation.
It's re-using the "views" from the river pages like the `/updates` page and I think the styling is good enough for such a seldom used feature.
1. Bookmark some reports, jobs and training
2. Go to your account >  bookmarks
3. Check that there the tab navigation appears and that the links show the proper bookmarks4.

[RW-221] Add tab navigation for bookmarks

---

composer.patches.json
patches/core--drupal--3008292-image-upload-validators.patch

Refs: RW-15
This adds the patch from https://www.drupal.org/project/drupal/issues/3008292 so that the upload validators (dimensions, size, file extensions) are respected when uploading an image via the media library (ex:  blog posts).
1. Create a new blog post, click add an image
2. Upload an image that doesn't have the proper dimensions (ex: https://reliefweb.int/sites/reliefweb.int/files/resources/afg_ocha_250px.png)
3. Check that the upload is allowed even though the width is lower than 700px
4. Try with https://reliefweb.int/sites/reliefweb.int/files/resources/afg_ocha_1000px.png for example, to confirm the upload also works.
1. Run `composer install` to patch core
2. Follow steps (1) and (2) from above, there …

[RW-15] Media image upload validation

---

docker/etc/nginx/apps/drupal/drupal.conf

Refs: OPS-8495
Copy of the changes from https://github.com/UN-OCHA/docker-images/pull/306 to update RW's modified version of drupal.conf.
**Note:**  the only difference between the RW's drupal.conf file and the one from the base docker image is the rules for the sitemap.xml and sitemap.xsl. The `location = /sitemap.xml` is too specific to be overridable by another rule so unfortunately we currently have to keep the RW's drupal.conf.

[OPS-8495] Add nginx rule for derivative images to reduce Drupal hits

---

html/themes/custom/common_design_subtheme/templates/layout/html--home.html.twig

fix: adjust icon sprite path in home html template override so telegram icon displays
Refs: RW-680

RW-680 Fix Telegram icon on homepage

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceInterface.php
html/modules/custom/reliefweb_moderation/src/Services/CountryModeration.php
html/modules/custom/reliefweb_moderation/src/Services/DisasterModeration.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/modules/custom/reliefweb_moderation/src/Services/SourceModeration.php

Refs: RW-681
The logic for deciding whether or not to set the drupal status field to 0 or 1 was faulty for the announcement, resulting in the status field to be always 0 preventing published announcements from being displayed on the homepage.
1. Create a new announcement, save as draft
2. Check that the announcement page is not accessible to anonymous or normal users but that editors can see it
3. Check that the announcement does **not** appear on the homepage
4. Save the announcement as published
5. Check that the announcement page is not accessible to anonymous or normal users but that editors can see it
6. Check that the announcement appears on the homepage
Ideally the following tests should be conducted for all the other existing main content types (jobs, training, disasters etc.):
1. …

[RW-681] Ensure that the entity publication status and moderation status are in sync

---

docker/Dockerfile
docker/etc/nginx/custom/03_disaster_map.conf
docker/etc/nginx/custom/03_mapbox.conf
docker/etc/nginx/sites-enabled/02_mapbox_proxy_cache.conf
html/modules/custom/reliefweb_disaster_map/js/disaster-map.js
html/modules/custom/reliefweb_disaster_map/js/mapbox.js
html/modules/custom/reliefweb_disaster_map/reliefweb_disaster_map.libraries.yml
html/modules/custom/reliefweb_disaster_map/reliefweb_disaster_map.module
html/modules/custom/reliefweb_disaster_map/reliefweb_disaster_map.routing.yml
html/modules/custom/reliefweb_disaster_map/src/Controller/DisasterMap.php
html/modules/custom/reliefweb_disaster_map/src/DisasterMapService.php
html/themes/custom/common_design_subtheme/templates/layout/html--disaster-map.html.twig
html/themes/custom/common_design_subtheme/templates/layout/page--disaster-map.html.twig

Refs: RW-689
This adds a route to embed disaster maps at `/disaster-map` or `/disaster/map/XX` where `XX` is a list of disaster type codes separated by a `-`.
To avoid excessive requests to the mapbox API, they are proxied and cached via nginx.
In addition, the access token is injected server side via a `MAPBOX_TOKEN` env variable visible to nginx.
**Notes**
[OPS-8731] is the ticket to add the env variable.
[OPS-8731]: https://humanitarian.atlassian.net/browse/OPS-8731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
**Tests**
1. Make sure the `MAPBOX_TOKEN` (same value as the `reliefweb_distater_map.settings`'s `mapbox_token` config value) is available. This can be added via the `docker-compose.yml` for the local stack.
2. Checkout the branch …

[RW-689] Embeddable disaster map

---

config/filter.format.markdown_editor.yml

Refs: RW-690
This allows `<br>` in fields using the `markdown_editor` text format (jobs, training) so that soft line breaks in imported content or entered in the editor via `shift + enter` are respected when rendering the field's content.
**Before checking out the branch**
1. Edit or create a job, add some text in the description, use `shift + enter` to break the text into 2 lines.
2. Save and check that the 2 lines are rendered as one (they appear as being separated by a space).
**After checking out the branch**
1. Import the config change (`drush cim`).
2. Edit or create a job, add some text in the description, use `shift + enter` to break the text into 2 lines.
3. Save and check that the 2 lines are rendered as 2 lines.

[RW-690] Fix line break

---

composer.lock
html/modules/custom/reliefweb_moderation/js/moderation.js
html/modules/custom/reliefweb_rivers/js/advanced-search.js

Refs: RW-693
This enables closing the filter dialog with `Escape` and wraps the focus inside the dialog in the river filters (ex: /updates) to improve the keyboard navigation.
It also fixes an existing issue when pressing escape in the moderation backend.
1. Checkout the branch and go to `/updates`
2. Open a filter (ex:  Country)
3. Check that the focus is wrapped (add -> first input etc.)
4. Check that the dialog closes when pressing `Escape` similarly to clicking `Cancel`

[RW-693] Filter accessibility

---

html/modules/custom/reliefweb_rivers/src/Controller/SearchConverter.php

Refs: RW-696
This catches and logs error when generating the JSON output of a search conversion when the input is invalid.
1. go to `/search/converter/json?appname=1%00%C0%A7%C0%A2%252527%252522&search-url=https%3A%2F%2Freliefweb.int%2Fupdates%3Fsearch%3Dthe%26view%3Dheadlines` on your local
2. check there is an uncaught exception
1. go to `/search/converter/json?appname=1%00%C0%A7%C0%A2%252527%252522&search-url=https%3A%2F%2Freliefweb.int%2Fupdates%3Fsearch%3Dthe%26view%3Dheadlines` on your local
2. check that the result is a JSON object with `Invalid input` and that the page status is 400.

[RW-696] Catch exception in search conversion when input is invalid

---

html/modules/custom/reliefweb_rivers/js/advanced-search.js

Refs: RW-697
This adds the `selected` attribute to the first option in the river filters using a `select` element (ex:  disaster type on /updates).
Note: this doesn't really improve anything in terms of accessibility. It's just to have check1st shut up.

[RW-697] Filter select accessibility

---

html/modules/custom/reliefweb_rivers/js/advanced-search.js
html/modules/custom/reliefweb_rivers/src/AdvancedSearch.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-advanced-search.html.twig

Refs: RW-694
This adds sections with a heading for the selected filters, apply/cancel filters and list of filters to ease navigation when using a screenreader.
Note: I investigated other options like the `accesskey` attribute or javascript handling to be able to more easily submit the form with the selected filters without having to navigate back up to the "apply filters" button after selecting a filter (ex: disaster type on /updates) but that interfered with natural browser or system shortcuts notably. So adding those headings is the softest touch for now.

[RW-694] Apply filters accessibility

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php

Refs: RW-701
This adds a `DISTINCT` to the main query of the moderation pages to ensure the counting of the document is correct.
1. Create or edit a report, add a dummy revision comment, save.
2. Repeat (1).
3. Go to `/moderation/content/report`, select `reviewed date` filter and today's date (so it catches the modification from (1) and (2)).
4. Add a `title` filter with the title of the node modified in (1)
5. There should be only 1 record in the list but the total should be 2 (or more).
Repeat (3) and (4) but this time the total in (5) should be `1`.

[RW-701] Fix record total in moderation pages

---

html/modules/custom/reliefweb_entities/src/Entity/Report.php

Refs: RW-702
This adds adds an option to use the short URL (`https://reliefweb.int/node/123456`) instead of the aliased URL in the publication notifications.
1. Edit a report, add an email address to the `notify` field, save
2. Open local mailhog, check that the report URL in the publication notification email contains the aliased URL
Repeat the above but this time the email should contain the short URL.

[RW-702] Use shortlink in publication notifications

---

config/field.field.node.job.field_source.yml

Refs: RW-703
This simply adds "Please use corporate email domain for your job submissions." at the end of the organization field's descriptions on the job form.
1. Check out the branch
2. Run `drush cim`
3. Go to `/node/add/job` and check that the text "Please use corporate email domain for your job submissions." appears at the end of the organization field's description

[RW-703] Add extra info to job source field's description

---

html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/common_design_subtheme/components/rw-entity-text/rw-entity-text.css
html/themes/custom/common_design_subtheme/js/cd-dropdown.js
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_entities/reliefweb-entities-entity-text.html.twig

Refs: RW-646
This moves the "show/hide description" toggler for countries and disasters after the description to preserve the keyboard navigation order (visual order was different than source order) to improve accessibility.
It also set the focus on the description title when expanding the description to make it easier for the user to read the description and navigate through it with the keyboard.
When pressing the "hide description", the page scrolls to the description toggler button which provides a consistent experience across browsers while otherwise the user can be sent much lower in the page (ex: Maps) depending on the browser.
For that, this PR intoduces some improvements and changes to the `cd-dropdown.js`:
- New methods to get the toggler from the toggable and vice versa using …

[RW-646] Disaster/country description visibility toggler

---

html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebImportInfo.php

Refs: RW-708
This set the maxlength for the import feed info fields on the source form to a value compatible with the database storage size to avoid truncating a 128 characters.
1. Go to `/taxonomy/term/2865/edit` for example, and a URL with more than 128 characters in the `Feed URL` field at the bottom of the form
2. Save and check that the URL has been truncated to 128 characters
Repeat the above but this time the URL should not be truncated.

[RW-708] Set proper max length for the import feed info fields

---

html/modules/custom/reliefweb_entities/src/Entity/Topic.php
html/modules/custom/reliefweb_files/src/Controller/FileDownloadController.php
html/modules/custom/reliefweb_files/src/Controller/ImageStyleDownloadController.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFile.php
html/modules/custom/reliefweb_guidelines/src/Form/GuidelineForm.php
html/modules/custom/reliefweb_key_figures/src/Services/KeyFiguresClient.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_rivers/src/AdvancedSearch.php
html/modules/custom/reliefweb_rivers/src/Controller/SearchConverter.php
html/modules/custom/reliefweb_rivers/src/Controller/SearchResults.php
html/modules/custom/reliefweb_rivers/src/Parameters.php
html/modules/custom/reliefweb_rivers/src/RiverServiceBase.php
html/modules/custom/reliefweb_rivers/src/Services/SourceRiver.php

Refs: RW-710
This adds some validation to all the places where we retrieve query parameters to avoid unexpected behaviors (like uncaught exception) when the parameter is invalid (ex `search[]=whatever` instead of `search=whatever`).
Compare with prod where the pages should show a "The website encountered an unexpected error. Please try again later.".
1. `/updates?search[]=whatever` (expected: parameter ignored)
2. `/updates?view[]=whatever` (expected: parameter ignored)
3. `/updates?advanced-search[]=whatever` (expected: parameter ignored)
4. `/updates?legacy-river[]=country/afg`  (expected: parameter ignored)
5. `/search/results?search[]=whatever` (expected: parameter ignored)
6. `/country/afg?figures[]=all` (expected: parameter ignored; it's already also ignored on prod)
7. …

[RW-710] Fix validation of query parameters

---

composer.patches.json

Refs: RW-709, OPS-8841
This adds a patch for the core issue with the page query parameter: https://www.drupal.org/project/drupal/issues/3143617
1. Go to `/updates?page[]=2` for example, this should show "The website encountered an unexpected error. Please try again later."
1.  Run `composer install` to patch core
2.  Go to `/updates?page[]=2` for example, this should show the first page of the updates (the page parameter is ignored as it's invalid).

[RW-709] Fix core issue with pager query parameter

---

html/modules/custom/reliefweb_utility/src/Helpers/HtmlSanitizer.php
html/modules/custom/reliefweb_utility/tests/src/Unit/HtmlSanitizerTest.php
html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
html/themes/custom/common_design_subtheme/templates/form/input--submit.html.twig

Refs: RW-712
This includes 2 fixes to improve compatibility of the forms with translation tools (like Chrome's page translation):
1. Use `<button>` instead of `<input>` for submit buttons in order to preserve the `value` attribute that Drupal uses to identify the clicked button. (For buttons, the text inside `<button>LABEL</button>` is translated while for input of type submit, the value is translated.)
2. Strip the `<font>` elements in the sanitizer, keeping the relevant children instead of removing the elements completely. Chrome page translation for example wraps all the translated text inside `<font style="vertical-align: inherit;">...</font>` for whatever reason.
(2) above is already checked by the unit tests so only (1) needs testing:
1. Using …

[RW-712] Fixes for translated forms.

---

html/modules/custom/reliefweb_meta/reliefweb_meta.module
html/modules/custom/reliefweb_rivers/src/AdvancedSearch.php
html/modules/custom/reliefweb_rivers/src/RiverServiceBase.php
html/modules/custom/reliefweb_rivers/src/RiverServiceInterface.php
html/modules/custom/reliefweb_rivers/src/Services/DisasterRiver.php
html/modules/custom/reliefweb_rivers/src/Services/JobRiver.php
html/modules/custom/reliefweb_rivers/src/Services/ReportRiver.php
html/modules/custom/reliefweb_rivers/src/Services/TrainingRiver.php

Refs: RW-705
This changes the generic page description of the rivers when there are selected filters to help search engines notably differentiate between those pages.
So for example [this search query](https://reliefweb.int/updates?advanced-search=%28S1275%29.%28DT4642_T4595%29_%28DA20200301-%29_%21%28OT273%29) will have the description:
> Updates with organization: World Health Organization (WHO) or with disaster type: Epidemic and theme: Health and with posting date on reliefweb: after 2020/02/29 and without organization type: Media
instead of the generic when there is no filter or search query:
> Your gateway to all content to date. Search and/or drill down with filters to narrow down the content.
1. Checkout this branch
2. Go to a river (ex: /updates), select some filters and apply
3. …

[RW-705] se selected filters and search for river page description

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php

Refs: RW-717
This restricts the fix from RW-701 (`distinct()`) to only apply when there is a filter on a revision table as it's the source of the duplication. This improves the performances for queries which already return unique results.
Note: previous PR with the fix from RW-701: https://github.com/UN-OCHA/rwint9-site/pull/502
1. Check out the latest develop
2. Go to `/moderation/content/report`, check how long it takes to load
3. Add a review date filter for example, apply and take note of the totals
1. Go to `/moderation/content/report`, check how long it takes to load => it should be faster than (2) above
2. Add the same date filter as (2) above, apply and check that the totals are the same.

[RW-717] Fix query performance on moderation pages

---

html/modules/custom/reliefweb_rivers/src/Controller/SearchConverter.php
html/modules/custom/reliefweb_rivers/src/RiverServiceBase.php

Refs: RW-718
This ensures the Cache-Control header for the RSS feeds (ex: /updates/rss.xml) and the json output of the search converter is properly set so that varnish can cache the pages.
Note: this requires that `$config['system.performance']['cache']['page']['max_age']` is properly set in the `settings.local.yml` file.
1. Check the cache control header of `/updates/rss.xml`, it should be  `private`
2. Check the cache control header of `/search/converter?appname=test&search-url=https%3A//rw9.test/updates`, it should be private
Repeat the above but this time the cache-control header should be `max-age=XX, public` where `XX` is the value of `$config['system.performance']['cache']['page']['max_age']` or `60` if using …

[RW-718] Fix cache control of RSS feeds and JSON output

---

html/modules/custom/reliefweb_users/src/Form/UserPageFilterForm.php

Refs: RW-724
This fixes the exception thrown when using the "posted" filter on the people page.
1. Go to `/admin/people`
2. Check "Job" for example under "Posted"
3. Click "Filter"
4. Cry
Repeat the above but this time at (4), after a few seconds (because the query is slow with this filter), you should see the properly filtered list of users.

[RW-724] Fix posted filter on people page

---

html/modules/custom/reliefweb_bookmarks/reliefweb_bookmarks.routing.yml
html/modules/custom/reliefweb_bookmarks/src/Controller/UserBookmarksController.php
html/modules/custom/reliefweb_subscriptions/reliefweb_subscriptions.routing.yml
html/modules/custom/reliefweb_subscriptions/src/Controller/SubscriptionController.php
html/modules/custom/reliefweb_user_posts/reliefweb_user_posts.routing.yml
html/modules/custom/reliefweb_user_posts/src/Controller/UserPostsPage.php

Refs: RW-725
This adds `/user/*` routes and associated controllers/methods for the bookmarks, posts and subscriptions user pages for the current user so we can add menu items under the new "my account" dropdown added in CD 7.4.
1. Checkout this branch and clear the cache (`drush cr`)
2. Log in with a user.
3. Confirm that the `/user/bookmarks`, `/user/notifications` and `/user/posts` redirect to the corresponding `/user/{uid}/*` pages.

[RW-725] User routes

---

docker/etc/nginx/apps/drupal/drupal.conf

Refs: OPS-8834
This adds the rule from https://github.com/UN-OCHA/docker-images/pull/320 to the `drupal.conf` to refuse to pass weird index.php<something> URLs to Drupal.
This is sadly needed because RW uses a custom `drupal.conf` file for the xmlsitemap handling.
*Before checking out this branch*
1. Go to `https://LOCAL.test/index.phppouet` (change LOCAL with your local site domain obviously)
2. Check that you get an error
*After checking out this branch*
1. Rebuild the site image (`make`) and container to take into account the change
2. Go to `https://LOCAL.test/index.phppouet`
3. Check that you get a 404 from nginx

[OPS-8834] Refuse to pass weird index.php<something> URLs to Drupal.

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/reliefweb_entities.services.yml
html/modules/custom/reliefweb_entities/src/EventSubscriber/AccessDeniedToNotFound.php
html/modules/custom/reliefweb_utility/src/Helpers/EntityHelper.php
html/modules/custom/reliefweb_utility/tests/src/ExistingSite/EntityHelperTest.php
html/themes/custom/common_design_subtheme/templates/layout/page--404.html.twig

Refs: RW-721
This returns a 404 instead of 403 for inaccessible bundle entities (jobs, countries etc.).
1. Log in as an editor, look for an unpublished job, copy the URL
2. Log out or open another browser or private window
3. Go to the job URL on the production site and check that it's a 403
4. Go to the job URL on the local site and check that it's a 404 with "The job TITLE OF THE JOB is no longer available" message

[RW-721] Show 404 instead of 403 for inaccessible entities

---

composer.json
composer.lock
html/themes/custom/common_design_subtheme/components/rw-admin-menu/admin-menu.js
html/themes/custom/common_design_subtheme/components/rw-admin-menu/rw-admin-menu.css

Refs: RW-726
This upgrades to the CD 7.4 and adjusts some css/js for the admin menu.
After upgrading,  and logged in as an Editor, the site's top header will look like (A):
Or, if https://github.com/UN-OCHA/common_design/pull/362 was merged, like (B):
As a normal user, it will look like that (C):
Or, if https://github.com/UN-OCHA/common_design/pull/362 was merged, like (D):
**Note:** (B) and (D) are also the expected result **after modifying the menu structure** as per CD 7.4's release notes with or without https://github.com/UN-OCHA/common_design/pull/362. 
**Extra**
If https://github.com/UN-OCHA/rwint9-site/pull/533 was merged and after adding the `user/*` sub menu items, like (E):
Or as an Editor (F):
1. Run `composer install` to upgrade to the CD 7.4
2. Run `drush cr` to clear the …

[RW-726] Upgrade to CD 7.4

---

html/modules/custom/reliefweb_rivers/src/Services/TrainingRiver.php

Refs: RW-733
This simply removes the exclusion of the "other" language for the training language field in the training river.

[RW-733] Enable 'other' language in training language filter

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/src/Entity/Job.php
html/modules/custom/reliefweb_entities/src/Entity/Report.php
html/modules/custom/reliefweb_entities/src/Entity/Training.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/Services/JobModeration.php
html/modules/custom/reliefweb_moderation/src/Services/TrainingModeration.php
html/modules/custom/reliefweb_utility/src/Helpers/ReliefWebStateHelper.php

Refs: RW-736
This adds a "Course/Event language" filter to the training moderation backend form, renames "Language" to "Advertisement Language" and limits the languages and themes returned by the autocomplete, to be consistent with the training form.
Excluding irrelevant values from the autocomplete suggestions is also applied to the theme and country filters for jobs to be consistent with the job form.
*Note:  make sure you have a recent enough DB so the `state` has the correct values*
1. Check out this branch
2. Clear the cache
3. Open `/moderation/content/training`
4. Check that the "Advertisement Language" and "Course/Event Language" filters are present in the dropdown
5. Select "Advertisement Language", type "Other", there should be no suggestion, type "Spanish", it should appear
6. …

[RW-736] Add training language backend filter and restrict autocomplete suggestions

---

config/core.menu.static_menu_link_overrides.yml

Refs: RW-738
This makes sure that the "expanded" property of the user menu is preserved after a deployment so that the "View dashboard", "View my posts" links etc. appear in the user menu dropdown.
1. Get a new light DB, restore it etc.
2. Checkout this branch
3. Import the config (drush cim) and clear the cache
4. Confirm that the "View dashboard" and other user links appear in the dropdown user menu (My account)

chore: store the configuration for the user menu account

---

html/modules/custom/reliefweb_rivers/js/advanced-search.js

Refs: RW-741
This fixes the logic regarding the advanced search checkbox which was preventing it from being deselected.
1. Check out this branch
2. Go to a river page
3. Check the "advanced search" checkbox at the bottom of the filters
4. Uncheck it
5. Add a filter (ex:  country)
6. Check the "advanced search" checkbox
7. Uncheck it -> there should be a popup asking for confirmation. Press cancel and confirm nothing changed and the checkbox is still checked.
8. Repeat (7) but this time press "ok", this should reload the page with the filter gone and "advanced search" should be unchecked

[RW-741] allow unselecting the advanced mode checkbox in rivers

---

html/modules/custom/reliefweb_rivers/src/Services/SourceRiver.php
html/modules/custom/reliefweb_utility/src/Helpers/TextHelper.php
html/modules/custom/reliefweb_utility/tests/src/Unit/TextHelperTest.php

Refs: RW-740
This updates the text helper to trim all Z and C unicode categories (notably to remove \u200b (zero width space) and trim the taxonomy term names when building the letter navigation on the /organizations page.
1. Check if you have the "CorpsAfrica" source (/organization/corpsafrica), if not grab a recent light DB dump
2. Clear the cache
3. Check the `/organizations` page, there should be a blank space in the letter navigation between C and D
1. Clear the cache
2. Go to `/organizations`, the blank "letter" should be gone
3. Edit the `/organization/corpsafrica` source, copy the name in your text editor (or something that can show invisible characters like your terminal), it should show that the name starts …

[RW-740] Extended text trimming

---

html/modules/custom/reliefweb_homepage/src/Controller/Homepage.php
html/modules/custom/reliefweb_rivers/src/Services/DisasterRiver.php

Refs: RW-746
This uses the `event` date to sort disasters to match the changes in the API from RW-594.
The disasters are now sorted by event date first and then ID (to have most recently created one first) for those with the same event date.
1. Update the most recent disaster (latest ID), set the event date to yesterday and save
2. Update the second most disaster (second lastest ID), set the event date to today and save
3. Confirm that the homepage and /disasters page have the same order with (2) first and (1) second
4. Update (1), set the event date to today and save
5. Confirm that the homepage and /disasters page have the same order with (1) first and (2) second

[RW-746] Use event date for sorting disasters

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module

Refs: RW-745
The cron code that published embargoed documents is missing a crucial condition to only publish reports with the `embargoed` status.
Note: the embargo date is in UTC so add/substract your timezone's offset.
1. Create or edit a report, set the embargo date to one/two minutes after your current time (+/- your timezone offset), save as `draft`
2. Wait until the time is passed and run `drush cron`
3. Check the draft document was published with the "Embargoed document automatically published..." message
1. Repeat the above but this time the `draft` report should not be published and stay as `draft`
2. Repeat the above but save as `on-hold` for example, this time the document should be published after running …

[RW-745] nly publish embargoed documents if they have the embargoed status

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/src/OpportunityDocumentTrait.php
html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebLinks.php
html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebUserPostingRights.php
html/modules/custom/reliefweb_import/src/Command/ReliefwebImportCommand.php
html/modules/custom/reliefweb_moderation/src/Commands/ReliefWebModerationCommands.php
html/modules/custom/reliefweb_moderation/src/Services/SourceModeration.php

Refs: RW-747
This explicitly sets the revision creation time when creating a revision manually. Without that the previous revision timestamp is used.
1. Edit a job source (allowed content format = job), save it as inactive, there should be revision entry with "inactive"
2. Create a job with that source, publish it
3. Check the source history, there should be a new revision entry with the "active" status, the date for this revision should be the same as the inactive one
Repeat the above but this time, the latest "active" revision should have a different timestamp than the "inactive" revision before it.

[RW-747] pecify revision creation time when manually creating revisions

---

html/modules/custom/reliefweb_files/src/Plugin/Field/FieldType/ReliefWebFile.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFile.php

Refs: RW-751
This fixes an issue with the download file name of report attachments when the extension is not lower case.
1. Checkout the branch and clear the cache
2. Edit or create a report and fill in the mandatory fields
3. Upload an attachment with the extension in **upper case** (ex: .PDF)
4. Check that the download file name (under "view file name details") is fine with either `PDF` or `pdf` as extension.
5. Leave it as `PDF` (upper case) and save the report and download the file to confirm it has the `PDF` extension
6. Edit the report again, change the extension to `pdf` (lower case) and save and download and check the extension is `pdf`
7. Edit the report again, this time, check that `PDF` (upper case) is not allowed (expected behavior because the download file name's original …

[RW-751] Allow original extension in download file name validation pattern

---

html/modules/custom/reliefweb_rivers/src/Services/SourceRiver.php

Refs: RW-753
This fixes the filter to get the list of publications for the sources.
1. Checkout this branch and clear the cache
2. Go to /organizations, and check that some organization show something like the screenshot above (may need to use letter filter or pagination to find a source with content when using the slim DB)

[RW-753] Use proper value for filter for source publications API queries

---

html/modules/custom/reliefweb_entities/src/Access/EntityAccessCheck.php

Refs: RW-755
This fixes the access to taxonomy term pages (all but countries, disasters and sources) that are supposed to be only accessible to people who can edit them.
2. Try to access term pages (ex: /career-categories/administrationfinance, /country/afg) as an anonymous user --> should get a 404 for all pages except for countries, disasters and sources.
3. Do the same as a normal authenticated user -> same results
4. Do the same as a user with the Editor role -> same results
5. Do the same as a user with the Webmaster role -> should be able to access the term pages

[RW-755] Fix access to taxonomy term pages

---

html/modules/custom/reliefweb_rivers/src/AdvancedSearch.php

Refs: RW-754
Sort suggestions with the same score alphabetically to improve ordering.
1. Before checking out this branch, take a screenshot or note the results of using `af` as query for the `organizations` filter on the `/updates` page.
2. After checking out this branch and clearing the cache, search for `af` as well, and confirm that the results look a bit more ordered.
See reference ticket for some example to confirm.

[RW-754] Better ordering of suggestions in river filters

---

html/modules/custom/reliefweb_fields/components/reliefweb-user-posting-rights/reliefweb-user-posting-rights.js

Refs: RW-760
This PR ensures changes to the notes field are saved when nothing else changes.
1. Checkout the branch and clear the cache
2. Find a source, click the "User posting rights" tab to edit the posting rights, add an entry with some comment. Save.
3. Edit again the rights, this time only change the notes and click save and confirm that the notes are showing the modifications.

[RW-760] save changes to user posting rights notes when nothing else changes

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php

Refs: RW-772
This PR fixes an issue when using a date range for some date field in the moderation backend, like the "registration deadline" for training.
1. Go to /moderation/content/disaster, select "creation date" as filter and enter a start and end dates.
2. Filter and check there is no error and the "disaster date" column reflects the selected filter.

[RW-772] Fix date range filter in moderation backend

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/Services/CountryModeration.php
html/modules/custom/reliefweb_moderation/src/Services/DisasterModeration.php
html/modules/custom/reliefweb_moderation/src/Services/SourceModeration.php

Refs: RW-772
This adds and renames date filters on the country, disaster and source moderation backends.
1. Checkout the branch, clear the cache
2. Go to `/moderation/content/country`, check that there is a "Change date" filter. Select a date, filter and confirm that it matches the "updated" column
3. Go to `/moderation/content/disaster`, check that there is a "Disaster date" "change date" filter. Select a date, filter and confirm that it matches the "disaster date" column
4. Go to `/moderation/content/disaster`, check that there is a "Creation date" "change date" filter. Select a date, filter and open a disaster in the results, check the revision history at the bottom and confirm the disaster was indeed created on the selected date
5. Go to `/moderation/content/source`, check that there …

[RW-772] Date filters

---

assets/robots.txt.append

Refs: RW-806
Simple robots.txt rule to disable crawling of paginated rivers when they are filtered (other query parameters).
2. Run `./local/install.sh -m -d` to recreate the site image and container with the updated robots.txt
3. Visit `/robots.txt` and confirm that the rule is present

[RW-806] Prevent bots from crawling rivers excessively

---

config/filter.format.markdown_editor.yml
html/modules/custom/reliefweb_utility/src/Plugin/Filter/ExternalLinkFilter.php

Refs: RW-812
This adds the target and rel attributes to external links to open in new tab for links inside fields using the markdown_editor (ckeditor 5) text format.
1. Checkout the branch, clear the cache, import the config
2. Create or edit a job or training, add some links in the body starting with `https://reliefweb.int` and your local domain like `https://rwint-local.test`.
3. Add links to external sites
4. Save
5. Confirm that the RW (prod and local) links do not have a target and rel attributes
6. Confirm that the external links have those attributes and open in new tab/window

[RW-812] Fix external links for jobs/training

---

docker/etc/nginx/custom/03_mapbox.conf

Refs: OPS-9699
This substitutes the mapbox token in the proxied mapbox responses.
2. Recreate the drupal container
3. Visit `/disasters`
4. Check the network tab (refresh if necessary), filter by `mapbox`
5. Check the content of any json file, the mapbox token should not be present (instead there should be `access_token=token`)

[OPS-9699] Remove mapbox token from mabox responses

---

html/modules/custom/reliefweb_utility/reliefweb_utility.module
html/modules/custom/reliefweb_utility/src/Entity/ImageStyleWithPipeline.php

Refs: RW-816
This makes sure the webp version of the derivative images are also removed when removing the derivative.

[RW-816] Fix: ensure webp derivative images are deleted

---

html/modules/custom/reliefweb_entities/src/Entity/Report.php

Refs: RW-818
Fix image style for interactive content that was overlooked in https://github.com/UN-OCHA/rwint9-site/pull/645.

[RW-818] Fix image style for interactive content

---

composer.json
composer.lock

Refs: OPS-9268
This module has not been used for some time https://github.com/UN-OCHA/rwint9-site/blob/main/config/core.extension.yml and can be removed completely.

chore: remove ckeditor contrib module

---

scripts/retagging/RW-829.php

[RW-829] Add script to retag MTI documents

---

PATCHES/common_design--default-logo-remove.patch
composer.patches.json

chore: create patch that removes logo from common_design base theme, add to patches file
See CD-519 for screenshots and details.
Once this patch is applied, the declaration in the common_design base theme rule that sets the UNOCHA logo as a background `  background:
linear-gradient(transparent, transparent),
url(../../../img/logos/ocha-logo-blue.svg) center no-repeat;`  is no longer present, which means we no longer have a reference to a missing image.
This will be tested after its deployed. If it has a positive impact on SEO, we will implement this properly in the base theme as described on CD-519

CD-519 Remove missing UNOCHA logo from base theme via patch

---

composer.json
composer.lock

This specifically avails of a recent update to the base theme to load fonts in a non-blocking manner. This was included in base theme release v9.2.3
See https://github.com/UN-OCHA/common_design/pull/448 for Font testing steps
There has since been another update for v9.3 which uses the SDC and rearranges the directory structure in the base theme.
https://github.com/UN-OCHA/common_design/releases/tag/v9.3.0
We shouldn't need to do anything to react to the v9.3 update since we do not reference any component's location using the directories, but instead use library extends when interacting with base theme components.
Refs: RW-841

RW-841 Update base theme to v9.3

---

composer.json
composer.lock

chore: update base theme to latest v9.3.1 to avail of CLS fix in OCHA Services
See release https://github.com/UN-OCHA/common_design/releases/tag/v9.3.1 and https://github.com/UN-OCHA/common_design/pull/458 for more.
Refs: RW-826

RW-826 Update base theme with CLS in OCHA Services performance improvement

---

PATCHES/common_design--default-logo-remove.patch
composer.patches.json

chore: base theme patch to remove ocha logo bg img
Refs: CD-519
See https://github.com/UN-OCHA/rwint9-site/pull/683

CD-519 Take 2 - Remove missing UNOCHA logo from base theme via patch

---

html/themes/custom/common_design_subtheme/templates/layout/page--ai--chat--popup.html.twig

Main PR: https://github.com/UN-OCHA/ocha_ai_chat/pull/8
This provides a leaner template so that our chat window doesn't load as much stuff. The Chat module still tried to `display:none` all the elements it doesn't need, but this avoids printing those elements entirely.

[RW-857] Companion to OCHA AI Chat PR

---

html/modules/custom/reliefweb_files/src/Plugin/Field/FieldType/ReliefWebFile.php

Refs: RW-878
This allows to pass additional parameters to the mutool command used to extract thumbnails from PDFs. Notably
- `-D` to fix issues with some PDFs like https://reliefweb.int/attachments/1fd03f18-18f8-44c5-8b36-18671f711a38/ar.pdf for which the thumbnail for the first page cannot be generated due to the way the PDF was created.
- `-w 1400` to generate a large enough image to have a less burry thumbnail, for example for https://reliefweb.int/sites/reliefweb.int/files/resources/ukr_ocha.pdf (PDF with vector map without proper dimensions)
These options can be set via drush for example (ex: `drush sset mutool_options -- "-D -w 1400"`).
1. Checkout the branch, clear the cache
2. Download https://reliefweb.int/attachments/1fd03f18-18f8-44c5-8b36-18671f711a38/ar.pdf
3. Create a report …

[RW-878] Mutool options

---

.github/workflows/run-tests.yml
docker/Dockerfile

Refs: [OPS-10120](https://humanitarian.atlassian.net/browse/OPS-10120)
As suggested in test output on https://github.com/UN-OCHA/rwint9-site/actions/runs/8051258709 :
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, aws-actions/configure-aws-credentials@v3, docker/login-action@v2.1.0, slackapi/slack-github-action@v1.23.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
See:
https://github.com/docker/login-action
https://github.com/aws-actions/configure-aws-credentials
https://github.com/actions/checkout
https://github.com/slackapi/slack-github-action
[OPS-10120]: https://humanitarian.atlassian.net/browse/OPS-10120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

chore: update actions as suggested

---

config/user.role.editor.yml
config/user.role.user_manager.yml
config/user.role.webmaster.yml
html/themes/custom/common_design_subtheme/templates/user/admin-menu.html.twig

Refs: RW-912
Save permissions and ensure roles which have access to some admin pages can view the admin menu with the relevant links.
1. Check out the branch, clear the cache, import the config
2. Log in as a webmaster
3. Click the "Admin menu" in the top header
4. Click the "Administration" link in the menu
5. Confirm that the admin page shown uses the Drupal default admin theme
6. Click the "Configuration" link in this admin page
7. Check that there is a "OCHA AI" section with a link to the logs and one to the chat config
8. Click those links to confirm they are accessible

[RW-912] Permissions and admin pages access

---

html/modules/custom/reliefweb_contact/reliefweb_contact.module

Refs: RW-907
Prefix the sender alias with the site name for the emails sent via the contact form.
1. Check out the branch, clear the cache
2. Log in as editor
3. Go to a different's user **contact** page
4. Select a category, enter a subject and body and send the email
5. Visit `https://mail.rwint-loca.test` to verify that something like the screenshot above appears with "ReliefWeb XXX" as sender and "[ReliefWeb - XXX] subject" as subject.
Note: make sure to have `https://mail.rwint-local.test` in your /etc/hosts if not already.

[RW-907] Ensure contact form sender alias is prefixed with the site name

---

composer.json
composer.lock

Refs: RW-867
1. Check out the branch, run composer install, clear the cache
2. Run `drush rapi-i --tag=test_rw_867 --limit=1 disaster`
3. Run `./local/exec.sh site curl http://elasticsearch:9200/reliefweb_disasters_index_test_rw_867/_mapping`
4. Check that there is a `uuid` appearing somewhere in the result.

[RW-867] Update API indexer to index UUIDs

---

html/themes/custom/common_design_subtheme/templates/layout/html--home.html.twig

Refs: RW-917
Add the `name` property to the JSON LD schema on the homepage.

[RW-917] Add missing name property to schema

---

html/themes/custom/common_design_subtheme/components/rw-document/rw-document.css

Refs: RW-919
Change the css rule to wrap text in links to use the more recent `overflow-wrap: anywhere` that tries not to break words if possible.
See ticket for screenshots of what to expect.
1. Checkout the branch, clear the cache
2. Edit/create a node, add some text with (a) a very long link containing words and another paragraph (b) with a very long URL.
3. Save or preview and confirm that for (a) the words are not broken and that the link text wraps at separators like spaces and that (b) is broken at some places in the URL and doesn't overflow.

[RW-919] Better wrapping of links

---

assets/robots.txt.append

Refs: RW-918
Add disallow rules for RSS and API search converter.
2. Recreate the image/container with `./local/install.sh -m -d`
3. Check the rules appear in `/robots.txt`

[RW-918] Add disallow rules for RSS and API converter

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/src/EventSubscriber/AccessDeniedToNotFound.php
html/modules/custom/reliefweb_entities/src/Routing/RouteSubscriber.php
html/themes/custom/common_design_subtheme/templates/layout/page--410.html.twig

Refs: RW-920
Returns a 410 for expired jobs/training and removes the title on 404 pages.
1. Checkout the branch, clear the cache.
2. Find an expired job in `/moderation/content/job` (or save on as expired)
3. Visit that job as anonymous user, confirm you get a 410 Gone **with** the `This job xxx is no longer available` message.
4. Find a draft or pending job
5. Visit it and confirm you get a 404  **without** the `This job xxx is no longer available` message

[RW-920] 410 for expired jobs/training and remove title on 404

---

html/themes/custom/common_design_subtheme/components/rw-admin-menu/admin-menu.js
html/themes/custom/common_design_subtheme/components/rw-admin-menu/rw-admin-menu.css
html/themes/custom/common_design_subtheme/templates/user/admin-menu.html.twig

Refs: RW-932
This fixes a regression from the upgrade to the latest CD for the RW admin menu.
1. Checkout the branch, clear the cache
2. Log in as an editor
3. Click the "admin menu" in the global header and check that the menu background stretches to the left and right borders (see screenshot).
4. Optionally, checkout v2.4.2 to confirm it's the same behavior.

[RW-932] Fix admin menu position

---

config/google_tag.container.default.yml

Refs: OPS-10242
This adds the new `hostname` setting added in google_tag v1.7.0.
1. Checkout the branch, clear the cache, import the config (ex: `local/install.sh -d`)
2. Visit `/admin/config/system/google-tag` and check the `hostname` column is `www.googletagmanager.com`

[OPS-10242] Add new hostname setting for google tag

---

composer.json
composer.lock
config/ocha_ai_tag.settings.yml
html/modules/custom/reliefweb_job_tagger/reliefweb_job_tagger.module
html/modules/custom/reliefweb_job_tagger/src/Plugin/QueueWorker/OchaAiJobTagTaggerWorker.php

Refs: RW-931
**Note**: the ocha_ai module is set to branch from https://github.com/UN-OCHA/ocha_ai/pull/23. That will need to be changed to a tagged release after the current ocha_ai open PRs are merged.
This adjusts a few things from https://github.com/UN-OCHA/rwint9-site/pull/734.
Each commit can picked up separately in case some of the changes in that PR are not welcomed.
Some of the main changes are:
1. Removal of the `entity->save()` in the `hook_entity_after_update` because it results in unnecessary double DB writes. Setting the tagging status to "queued" in the `presave` hook and queueing the entity in the `after_save` hook is enough.
2. The use of the `instructions` field of the ai tagger config form for the message displayed on the job form. This is to be able to adjust or remove …

[RW-931] Job tagging adjustments

---

html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php

Refs: RW-934
Temporarily always show the OCHA product field due to incompatibility of the states condition and Drupal 10.2.5 changes to the form state API which prevent posting OCHA content.

[RW-934] Fix: disable the state conditions for the OCHA production field due to incompatibility with Druapl 10.2.5

---

html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_form/js/widget.autocomplete.js

Refs: RW-934
This replaces the non-working Drupal form state logic with custom one to show/hide the OCHA product field when OCHA is selected.
1. Check out the branch, clear the cache
2. Create a new report `/node/add/report`
3. Fill in language, title, body, origin notes, country, primary country and content format
4. Check that the `OCHA product` field below the `Source` field is not present
5. Select a source other than OCHA, ex: UNDP, check that the `OCHA product` field is still not visible
6. Add `OCHA` as selection, check that the `OCHA product` field now appears
7. Remove `OCHA` from the selection, check that the `OCHA product` field disappears
8. Add `OCHA` back, remove `UNDP`, check that the `OCHA product` field is visible
9. Save
10. Edit the report, check that the `OCHA product` …

[RW-934] Fix OCHA product visibility on report form

---

html/modules/custom/reliefweb_subscriptions/reliefweb_subscriptions.services.yml
html/modules/custom/reliefweb_subscriptions/src/AmazonSesMessageBuilder.php
html/modules/custom/reliefweb_subscriptions/src/EmailWithBcc.php
html/modules/custom/reliefweb_subscriptions/src/ReliefwebSubscriptionsMailer.php

Refs: OPS-9523, RW-935
_This is against the [cafuego/ops-9523-amazon-ses](https://github.com/UN-OCHA/rwint9-site/tree/cafuego/ops-9523-amazon-ses) branch._
This PR adjusts the way emails are sent by the `amazon_ses` module to handle proper HTML formatting, extra headers and BCC.
**Important:** to work properly this assumes that the formatting of the message is still done by MimeMail so the `mail.profile.formatter` will have to be set to `mime_mail` for RW: https://github.com/UN-OCHA/tools-ansible/blob/977a2cc13d56c2ed66ca5f57942d660a91432201/modules/drupal/templates/settings.10.php.j2#L1276

[OPS-9523][RW-935] Amazon SES compatibility fixes

---

html/modules/custom/reliefweb_subscriptions/reliefweb_subscriptions.info.yml
html/modules/custom/reliefweb_subscriptions/reliefweb_subscriptions.services.yml

Refs: OPS-9523
Make Drupal happy and stop complaining about a missing service because it loads things out of order.

[OPS-9523] Fix missing logger channel complaint

---

html/modules/custom/reliefweb_job_tagger/reliefweb_job_tagger.module
html/modules/custom/reliefweb_reporting/reliefweb_reporting.module
html/modules/custom/reliefweb_reporting/src/Commands/ReliefWebReportingCommands.php

Refs: RW-938
This adds some logging of the manual changes made to jobs tagged by the AI.
It also adds a drush command to the reporting module to send weekly stats about the AI tagging (number of tagged jobs, number of jobs with themes/career categories changed manually).

[RW-938] Log manual changes to AI tagging

---

PATCHES/core--drupal--3418098-php-mailer.patch
composer.patches.json

Refs: RW-939
Tiny patch to avoid the following PHP notice when sending emails:
> str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in docroot/core/lib/Drupal/Core/Mail/Plugin/Mail/PhpMail.php line 114

[Rw-939] Add patch to prevent php notice from Drupal core PHP mailer

---

html/modules/custom/reliefweb_utility/src/Helpers/MarkdownHelper.php
html/modules/custom/reliefweb_utility/tests/src/Unit/MarkdownHelperTest.php

Refs: RW-940
Prevent parsing markdown **reference links**: `[foo]: /url` when displaying revision logs.

[RW-940] Prevent parsing reference links when converting revision logs

---

config/reliefweb_subscriptions.settings.yml
docker/etc/nginx/custom/04_unsubscribe.conf
html/modules/custom/reliefweb_subscriptions/config/install/reliefweb_subscriptions.settings.yml
html/modules/custom/reliefweb_subscriptions/config/schema/reliefweb_subscriptions.schema.yml
html/modules/custom/reliefweb_subscriptions/reliefweb_subscriptions.routing.yml
html/modules/custom/reliefweb_subscriptions/src/Controller/UnsubscribeController.php
html/modules/custom/reliefweb_subscriptions/src/ReliefwebSubscriptionsMailer.php

Refs: RW-885
This replaces the current unsubscribe links with one-click unsubscribe links.
It also adds the proper List-Unsubscribe* headers and removes cookie headers for the POST requests.
**Notes** 
- Make sure you have the local stack with mailpit or another tool the RW drupal site can send emails to.
- Make sure you have an instance of the RW API and that the RW local site can index content in it.
**Steps**
1. Checkout the branch, clear the cache, import the config
2. Truncate the subscriptions table: `drush sql-query "TRUNCATE reliefweb_subscriptions_subscriptions"`, `drush sql-query "TRUNCATE reliefweb_subscriptions_queue"`, `drush sql-query "TRUNCATE reliefweb_subscriptions_logs"`
3. Log in, go to your subscriptions page `/user/notifications`, subscribe to the headlines.
4. Create …

[RW-885] One-click unsubscribe links for notifications

---

html/modules/custom/reliefweb_subscriptions/src/Controller/UnsubscribeController.php
html/modules/custom/reliefweb_subscriptions/src/Form/UnsubscribeForm.php

Refs: RW-885
The `/user/notifications` already redirects to the `/user/{uid}/notifications` page when logged in so let's avoid exposing the user ID unnecessarily.

[RW-885] No need for personalized subscriptions page destination

---

html/modules/custom/reliefweb_job_tagger/src/Plugin/QueueWorker/OchaAiJobTagTaggerWorker.php

Refs: RW-942, RW-943
- Log errors from the `ocha_ai` tagger service to identify the affected nodes.
- Save tagging revisions with the system user to better identify them, and set the revision timestamp to avoid using the previous revision's one.

[RW-942][RW-943] Job tagging fixes

---

config/core.entity_form_display.node.report.default.yml
config/editor.editor.markdown.yml
config/editor.editor.markdown_editor.yml
config/field.field.node.report.body.yml
config/filter.format.guideline.yml
config/filter.format.html.yml
config/filter.format.markdown.yml
config/filter.format.markdown_editor.yml
config/filter.format.plain_text.yml
config/filter.format.token_markdown.yml
html/modules/custom/reliefweb_fields/README.md
html/modules/custom/reliefweb_fields/js/reliefweb_markdown_editor.js
html/modules/custom/reliefweb_fields/reliefweb_fields.libraries.yml
html/modules/custom/reliefweb_fields/reliefweb_fields.module
html/modules/custom/reliefweb_fields/src/EditorXssFilter/ReliefWebMarkdownXssFilter.php
html/modules/custom/reliefweb_fields/src/Plugin/Editor/ReliefWebMarkdownEditor.php
html/modules/custom/reliefweb_utility/src/Plugin/Filter/MarkdownFilter.php
html/themes/custom/common_design_subtheme/css/typography.css

Refs: RW-796
This sets the rich editor text format (ckeditor5 with some markdown conversion) as the default text format for reports similar to the jobs and training.
The default text format for existing content is still the `markdown` one to avoid losing data (the text can contain some extra stuff like image tracking code etc. tables which are really uncommon) but new reports use the `rich editor` text format.
To be able to switch between text formats without losing most of the content, this PR introduces some hack to convert the text between HTML (ckeditor 5) and markdown (textarea). See the comment in the `ReliefWebMarkdownXssFilter.php` file for mode details.
Jobs/training still continue to only use the Rich editor and should be unaffected by those changes (except for the addition of …

[RW-796] Allow use of the rich editor for reports

---

html/modules/custom/reliefweb_fields/js/reliefweb_markdown_editor.js

Refs: RW-975
Ensure the markdown version of a text field is saved when changing the editor from Rich editor to markdown
1. Create a report, fill in the form (with some bold, links, list etc. in the body) and save
2. Edit the report, change the text format of the body to "Markdown" (**do not change the content of the body field**)
3. Save
4. Edit the report, the content of the body field is HTML instead markdown
1. Clear the cache
2. Repeat the steps above but this time (4) should show markdown instead of HTML in the body field

[RW-975] Editor switch fix

---

html/modules/custom/reliefweb_job_tagger/src/Plugin/QueueWorker/OchaAiJobTagTaggerWorker.php

Refs: RW-978
**Note**: this a fix for the `v2.9.0` so the PR is against the `main` branch.
This revert the revision user change from https://github.com/UN-OCHA/rwint9-site/pull/802/commits/de10e81df6edf847d75fe775997ac13da41279f3. (The change for the timestamp is correct.)
Using the system user conflicts with https://github.com/UN-OCHA/rwint9-site/blob/56e52073fa5c7ce9211632c5fe0a39582d25959b/html/modules/custom/reliefweb_entities/src/OpportunityDocumentTrait.php#L21.

[RW-978] Fix: revert revision user for job tagger

---

config/seckit.settings.yml

Refs: OPS-10504
This adds back the `unsafe-eval` to issues with GTM...

[OPS-10504] Add back unsafe-eval for GTM compatibility

---

composer.lock
html/modules/custom/reliefweb_entities/src/DocumentTrait.php
html/modules/custom/reliefweb_entities/src/Entity/Report.php
html/modules/custom/reliefweb_utility/src/Helpers/DateHelper.php

Refs: RW-1001
- Update datepicker version with fix
- Update different places handling publication dates
**Note:** This requires a valid 
1. Checkout the branch, run composer install, clear the cache
2. Create a report, set the original publication date to 1 Jan 1970, check that this can be done via the datepicker
3. Check "bury"
4. Save
5. Go to `/updates`, then click "last" in the pager at the bottom and check that the document appears and 1 Jan 1970 is displayed for `posted` and `original publication date` <-- You need a valid installation of the API to test that (so the document is indexed)
6. Repeat 2 to 5 with a date before 1 Jan 1970, notably that the datepicker works

[RW-1001] Handle dates equal or before unix epoch

---

config/reliefweb_entities.settings.yml
html/modules/custom/reliefweb_entities/config/install/reliefweb_entities.settings.yml
html/modules/custom/reliefweb_entities/src/DocumentTrait.php
html/modules/custom/reliefweb_subscriptions/templates/reliefweb-subscriptions-content--blog.html.twig
html/themes/custom/common_design_subtheme/components/rw-social-media-links/rw-social-media-links.css
html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-social-menu.html.twig

Refs: RW-997
Social share now goes to X instead of twitter.com - the icon has already been changed:
The footer link also goes to x.com rather than twitter (again, the icon has already been changed):
Twitter and x links are now shown for organizations as X links:
I believe it's better to leave twitter ones as they are, rather than updating them in the database. If we have both an 'x' and a 'twitter' link, it will look odd so editors might be encouraged to remove one of them:
We're still using the word 'twitter' for the icons - and for the metatags x documentation still refers to 'twitter cards' etc.

chore: switch remaining twitter links to handle x instead

---

html/modules/custom/reliefweb_entities/src/DocumentTrait.php

Refs: RW-1001
This avoids deprecation notice when the date is NULL like ongoing training for example.

[RW-1001] More proper fix for node dates

---

composer.lock

Refs: RW-1047
Bump the ocha_ai module to 1.5.1.

chore: update ocha_ai module to 1.5.1

---

PATCHES/core--drupal--3467860-aggregation.patch
composer.patches.json

Refs: RW-1055
This adds the patch from the MR from https://www.drupal.org/project/drupal/issues/3467860 backported to Drupal 10.3.2 to solve the js/css aggregation issue.

[RW-1055] Add core patch for css/js aggregation

---

html/modules/custom/reliefweb_fields/src/Form/TaxonomyTermProfile.php
html/modules/custom/reliefweb_fields/src/Form/TaxonomyTermUserPostingRights.php

Refs: RW-1071
This ensures that the revision user and timestamp are correctly set when editing a term profile or user posting rights.

[RW-1071] Fix revision user/time for terms

---

PATCHES/openid_connect-3390668-6.patch
PATCHES/openid_connect_windows_aad-3346603-5.patch
composer.json
composer.lock
composer.patches.json
config/core.extension.yml
config/key.key.entraid_client_secret.yml
config/openid_connect.client.entraid.yml
config/openid_connect.settings.yml

Add and configure OpenID Connect. 
Refs: OPS-10834

feat: Start on the HID replacement journey.

---

config/core.extension.yml
config/user.role.editor.yml
config/user.role.webmaster.yml
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_fields/reliefweb_fields.info.yml
html/modules/custom/reliefweb_revisions/reliefweb_revisions.info.yml

Refs: RW-1076
This uninstalls the `taxonomy_term_revision` module since all of its functionalities are in Drupal core now (10.3+). The module itself will be remove from composer in another PR and deployment.

[RW-1076] Remove now redundant taxonomy_term_revision

---

html/modules/custom/reliefweb_reporting/reliefweb_reporting.module

Refs: RW-1078
New `jobs_changed_by_editors` field.
Ex:
```
{
"jobs_tagged_by_ai": 2738,
"career_categories_changed_by_editors": 1223,
"themes_changed_by_editors": 953,
"jobs_changed_by_editors": 1552
}
```

[RW-1078] Log number of jobs changed by editors for job tagging stats

---

html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_rivers/src/Services/ReportRiver.php
scripts/retagging/RW-1077.php

Refs: RW-1077
This does the following:
- Hide the "Interactive" content format in the report form unless editing an existing Interactive content.
- Hide the "Interactive" content format from the river filter.
- Add a script to archive the interactive content.

[RW-1077] Decommission interactive content

---

html/modules/custom/reliefweb_entraid/src/Controller/AuthController.php

Basically, this allows Drupal to initialize a session for the (anonymous) user so that the state token can be stored.
Refs: OPS-10834

fix: Return the response object, so Drupal can do its thing.

---

html/themes/custom/common_design_subtheme/components/rw-document/rw-document.css

Refs: RW-1093
Replace the rule to break long links with a more generic one to also break long strings outside of links.

[RW-1093] Ensure long text is properly broken in documents

---

.github/workflows/composer-update.yml

Refs: OPS-10284
The action fails because there is no `dev` branch for https://github.com/UN-OCHA/actions

[OPS-10284] Use main branch of github actions in composer-update workflow

---

html/modules/custom/reliefweb_entities/src/Entity/Report.php
html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php

Refs: RW-1058, RW-1111
- Adjust the logic for the status and message for contributors
- Adjust the logic for the origin fields

[RW-1058] Contributor fixes

---

html/modules/custom/reliefweb_post_api/schemas/v2/job.json
html/modules/custom/reliefweb_post_api/schemas/v2/report.json
html/modules/custom/reliefweb_post_api/schemas/v2/training.json

Refs: RW-831
Includes the information from https://unitednations.sharepoint.com/:w:/r/sites/OCHAIMB/Digital%20Services%20Section/06_Projects/ReliefWeb/ReliefWeb%20API/ReliefWeb%20POST%20API%20-%20starting%202024/ReliefWeb%20Post%20API%20%E2%80%93%20Editorial%20guidelines.docx?d=w6774e15ece2349e0813973d88c6e01b4&csf=1&web=1&e=muNaiv - and tries to gather everything into one place.
I was looking for a reference for this, but couldn't find one:
```
{
"description": "Must contain letters (any language).",
"pattern": "\\p{L}+"
},
```
I understand that `L` also includes numbers, punctuation, html tags, etc, but I'm not sure what it excludes.

docs: enhance descriptions in api schema

---

composer.json
composer.lock
config/core.extension.yml
config/ocha_entraid.settings.yml
html/modules/custom/reliefweb_entraid/README.md
html/modules/custom/reliefweb_entraid/reliefweb_entraid.routing.yml
html/modules/custom/reliefweb_entraid/tests/src/ExistingSite/ReliefwebEntraidLoginTest.php

Refs: OPS-10828, OPS-10896
This adds the https://github.com/UN-OCHA/ocha_entraid module and disable the `reliefweb_entraid` module (to be removed in another PR).
Note: permissions to access the login and registration forms are not yet set since we are still waiting for some approval (see OPS-10896) but that can be added via the UI and later saved to code (see https://github.com/UN-OCHA/rwint9-site/pull/960)

[OPS-10828] Add Entra ID login/registration

---

html/modules/custom/reliefweb_utility/src/TwigExtension.php

Refs: RW-1150
Prevent a php type error when the revision user of an entity revision is missing.

[RW-1150] Prevent issue with missing user entity in history

---

config/core.extension.yml
config/reliefweb_anti_spam.settings.yml
config/user.role.editor.yml
config/user.role.webmaster.yml
html/modules/custom/reliefweb_anti_spam/README.md
html/modules/custom/reliefweb_anti_spam/config/install/reliefweb_anti_spam.settings.yml
html/modules/custom/reliefweb_anti_spam/config/schema/reliefweb_anti_spam.schema.yml
html/modules/custom/reliefweb_anti_spam/reliefweb_anti_spam.info.yml
html/modules/custom/reliefweb_anti_spam/reliefweb_anti_spam.links.menu.yml
html/modules/custom/reliefweb_anti_spam/reliefweb_anti_spam.module
html/modules/custom/reliefweb_anti_spam/reliefweb_anti_spam.permissions.yml
html/modules/custom/reliefweb_anti_spam/reliefweb_anti_spam.routing.yml
html/modules/custom/reliefweb_anti_spam/src/Form/ReliefWebAntiSpamSettingsForm.php
html/modules/custom/reliefweb_anti_spam/tests/src/ExistingSite/ReliefWebAntiSpamTest.php
html/modules/custom/reliefweb_anti_spam/tests/src/Unit/ReliefWebAntiSpamTest.php
html/modules/custom/reliefweb_moderation/src/Helpers/UserPostingRightsHelper.php
html/modules/custom/reliefweb_utility/src/Helpers/TextHelper.php
html/modules/custom/reliefweb_utility/tests/src/Unit/TextHelperTest.php

Refs: RW-1155
This adds a `reliefweb_anti_spam` module with some rules to get rid of obvious spam attempts and possibly restrict the number of posts for a given period for unverified users.

[RW-1155] Add module to help against job/training post spamming

---

config/user.role.editor.yml
html/modules/custom/reliefweb_users/reliefweb_users.links.task.yml
html/modules/custom/reliefweb_users/reliefweb_users.module
html/modules/custom/reliefweb_users/reliefweb_users.permissions.yml
html/modules/custom/reliefweb_users/reliefweb_users.routing.yml
html/modules/custom/reliefweb_users/src/Controller/UserPostingRightsController.php

[RW-1161] Add user page with summary of posting rights

---

composer.json
composer.lock

Refs: OPS-10039
It has not been enabled for a long time - now there's a security issue
too.

chore: remove google_tag module

---

composer.json
composer.lock

Refs: updates
There was some version confusion in honeypot some months ago that meant we should insist on v2.1 before moving to 2.2. That happened in https://github.com/UN-OCHA/rwint9-site/pull/886 which links to the d.o issue.
I think we're okay to unpin the module again now. The changes from 2.1 to 2.2 are listed here: https://www.drupal.org/project/honeypot/releases/2.2.0

updates: unpin honeypot module

---

config/core.extension.yml

Refs: OPS-11317
Further to https://github.com/UN-OCHA/rwint9-site/pull/1004 and not properly tested, but I don't think Classy is being used anywhere - and uninstalling it doesn't seem to make any difference. It was removed from SLT when we upgraded to Drupal9 and also isn't yet Drupal 11 compatible: https://www.drupal.org/project/classy/issues/3461089

chore: remove classy theme too

---

composer.lock
config/ocha_content_classification.ocha_classification_workflow.node_report.yml
html/modules/custom/reliefweb_import/src/Plugin/OchaContentAnalyzableFieldProcessor/ReliefWebBodyProcessor.php

Refs: RW-1210
This enables the body field as analyzable field and uses a new field processor to prepend the title to the body field for better context. The body field is passed as attachment and so is handled the same way than attachments.
Note: this bumps the ocha_ai version to handle this approach.

[RW-1210] Support body as source for report classification

---

html/modules/custom/reliefweb_files/reliefweb_files.install
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldFormatter/ReliefWebFileFileName.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldFormatter/ReliefWebFileFileUrl.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldType/ReliefWebFile.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFile.php
html/modules/custom/reliefweb_files/src/Plugin/Validation/Constraint/ReliefWebFileHashConstraint.php
html/modules/custom/reliefweb_files/src/Plugin/Validation/Constraint/ReliefWebFileHashConstraintValidator.php
html/modules/custom/reliefweb_files/src/Plugin/Validation/Constraint/ReliefWebFileRealMimeTypeConstraint.php
html/modules/custom/reliefweb_files/src/Plugin/Validation/Constraint/ReliefWebFileRealMimeTypeConstraintValidator.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/EchoFlashUpdateImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/InoreaderImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/UnhcrDataImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/WfpLogClusterImporter.php
html/modules/custom/reliefweb_post_api/src/Exception/DuplicateException.php
html/modules/custom/reliefweb_post_api/src/Exception/ExceptionInterface.php
html/modules/custom/reliefweb_post_api/src/Plugin/ContentProcessorPluginBase.php
html/modules/custom/reliefweb_post_api/src/Plugin/ContentProcessorPluginInterface.php
html/modules/custom/reliefweb_post_api/src/Plugin/reliefweb_post_api/ContentProcessor/Report.php
html/modules/custom/reliefweb_post_api/tests/src/ExistingSite/Plugin/ContentProcessorPluginBaseTest.php

Refs: RW-1227
This adds a property to store the report attachment hash and a constraint to prevent duplication.
This also adjusts the post API to also handle file duplication and straight-up refuse submissions in that case.

[RW-1227] Store attachment hashes and prevent duplication

---

config/reliefweb_import.plugin.importer.wfp_logcluster.yml
html/modules/custom/reliefweb_import/config/schema/reliefweb_import.schema.yml
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/WfpLogClusterImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporterPluginBase.php

Refs: RW-1207
- proper mapping for maps in logcluster importer
- ensure the logcluser document path are to the main site not the api
- skip import of documents already manually posted
- make sure to use the document date for the original publication date not the last update to match the content on the log cluster site
- log cluster schema max age type
- add logcluster importer plugin setting to skip some document types

[RW-1207] Log cluster import fixes

---

html/modules/custom/reliefweb_rivers/src/Parameters.php

Using a temporary variable for readbility.

fix(chore): Avoid a deprecation warning by not passing a null into parse_str when a url has no query part.

---

html/modules/custom/reliefweb_files/src/Plugin/Field/FieldType/ReliefWebFile.php

Refs: RW-1308
Fix for the issues with the imports on the test envs after the weekly reset.

[RW-1308] Prevent type error when there is no file available to generate its hash
