composer.json
composer.lock
html/themes/custom/common_design_subtheme/README.md
html/themes/custom/common_design_subtheme/_tests/FooterMenu.test.js
html/themes/custom/common_design_subtheme/_tests/MainMenuDropdown.test.js
html/themes/custom/common_design_subtheme/_tests/MobileMenu.test.js
html/themes/custom/common_design_subtheme/_tests/OCHADropdown.test.js
html/themes/custom/common_design_subtheme/_tests/SearchDropdown.test.js
html/themes/custom/common_design_subtheme/build/styles.css
html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/common_design_subtheme/package.json
html/themes/custom/common_design_subtheme/sass/cd/_cd-variables.scss
html/themes/custom/common_design_subtheme/sass/cd/cd-header/_cd-logo.scss
html/themes/custom/common_design_subtheme/sass/cd/cd-header/_cd-nav.scss

Ticket: CD-270
Bump base theme to 4.0.0 and update subtheme.

[CD-270] Update base theme to 4.0.0

---

config/core.extension.yml
config/system.site.yml
html/modules/custom/reliefweb_homepage/README.md
html/modules/custom/reliefweb_homepage/reliefweb_homepage.info.yml
html/modules/custom/reliefweb_homepage/reliefweb_homepage.module
html/modules/custom/reliefweb_homepage/reliefweb_homepage.routing.yml
html/modules/custom/reliefweb_homepage/src/Controller/Homepage.php
html/modules/custom/reliefweb_homepage/templates/reliefweb-homepage-announcement.html.twig
html/modules/custom/reliefweb_homepage/templates/reliefweb-homepage-opportunities.html.twig
html/modules/custom/reliefweb_homepage/templates/reliefweb-homepage.html.twig

Ticket: RW-27
This adds a route and its controller for the homepage and ports the homepage components.
The most-read component will need to be refactored after the work on RW-23 and the announcement component as well after RW-16.

[RW-27] Add homepage route and controller

---

html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article-meta.html.twig

Make sure the end date is used...

[RW-24] Fix date range in meta template

---

html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-meta.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--disaster.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--report.html.twig
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--training.html.twig
html/themes/custom/common_design_subtheme/components/rw-entity-meta/rw-entity-meta.css
html/themes/custom/common_design_subtheme/templates/content/taxonomy-term--country--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/taxonomy-term--disaster--full.html.twig
html/themes/custom/common_design_subtheme/templates/content/taxonomy-term--source--full.html.twig

Ticket: RW-56
As discussed, this adds attributes for the labels and values of the meta information so that we can more easily target items that need special attention and notably hide the label only when necessary.

[RW-56] Add label and value attributes to entity meta to ease styling

---

html/themes/custom/common_design_subtheme/components/rw-headlines/rw-headlines.css

- update selector so country slug is correctly sized in headlines component

RW-39 Country slug in Headlines

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/rw-social-media-links/rw-social-media-links.css
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-dsr/reliefweb-digital-situation-report.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-entities/reliefweb-entities-entity-details.html.twig
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb-entities/reliefweb-entities-entity-social-media-links.html.twig

Add styles for Social Media Links and Details, define libraries and attach to template override, apply title class
https://trello.com/c/w13Ipg74/180-organization-details
https://trello.com/c/ZUJv6oIZ/179-organization-social-media-links
And unrelated, add the block title class to the DSR component.

RW-72 Organizations

---

html/modules/custom/reliefweb_migrate/reliefweb_migrate.install

[RW-67] Fix hook update in reliefweb_migrate

---

config/reliefweb_api.settings.yml
html/modules/custom/reliefweb_api/config/install/reliefweb_api.settings.yml
html/modules/custom/reliefweb_api/src/Services/ReliefWebApiClient.php
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/templates/reliefweb-entities-entity-image.html.twig
html/modules/custom/reliefweb_migrate/src/EventSubscriber/ProxySubscriber.php
html/modules/custom/reliefweb_rivers/src/Services/ReportRiver.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river-article--report.html.twig
html/modules/custom/reliefweb_utility/src/Helpers/UrlHelper.php

Ticket: RW-35
This adds the headline images on the homepage.
This also adds/modifies a few helpers to deal with legacy/stage URLs rewriting.

[RW-35] Headline images

---

docker/Dockerfile

Bump to the latest (PHP 8.0.9) version in Alpine 3.14, with an nginx DNS resolver fix and the crufty wddx.ini config file removed.

[OPS-7696] New PHP images

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.theme
html/themes/custom/common_design_subtheme/components/rw-book-menu/rw-book-menu.css
html/themes/custom/common_design_subtheme/components/rw-document/rw-document.css
html/themes/custom/common_design_subtheme/components/rw-form/rw-form--widget.css
html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
html/themes/custom/common_design_subtheme/components/rw-river/rw-river.css
html/themes/custom/common_design_subtheme/components/rw-toc/rw-toc.css
html/themes/custom/common_design_subtheme/templates/content/node-edit-form--announcement.html.twig
html/themes/custom/common_design_subtheme/templates/content/node-edit-form--blog-post.html.twig
html/themes/custom/common_design_subtheme/templates/content/node-edit-form--book.html.twig
html/themes/custom/common_design_subtheme/templates/content/node-edit-form--job.html.twig
html/themes/custom/common_design_subtheme/templates/content/node-edit-form--report.html.twig
html/themes/custom/common_design_subtheme/templates/content/node-edit-form--topics.html.twig
html/themes/custom/common_design_subtheme/templates/content/node-edit-form--training.html.twig

Mainly make sure all form fields are accounted for per content type, and note on the issue which ones are missing.
Some tweaks to form styles and TOC styles

RW-127 Node edit forms

---

composer.json
composer.lock

So we can avail of the form styles I am working on over on https://github.com/UN-OCHA/common_design/pull/254
This will also provide the recent changes from v5.0.0 release https://github.com/UN-OCHA/common_design/releases/tag/v5.0.0 needed for the Page title and the admin icon.

RW-125 Use cd-304-forms base theme branch

---

html/modules/custom/reliefweb_fields/reliefweb_fields.info.yml

@orakili: Travis is smarter than Jenkins.

[OPS-7797] Explicitly add the taxonomy depends.

---

composer.json
composer.lock
config/filter.format.token_markdown.yml
symfony.lock

Ticket: RW-156
This removes some leftovers of the now unused `token_filter` module.

[RW-156] Remove token filter leftovers

---

html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-footer.html.twig
html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-ocha.html.twig

RW-167 Update OCHA Services Related Platforms list

---

html/themes/custom/common_design_subtheme/components/rw-disasters/rw-disasters.css
html/themes/custom/common_design_subtheme/components/rw-local-tasks/rw-local-tasks.css
html/themes/custom/common_design_subtheme/components/rw-toc/rw-toc.css
html/themes/custom/common_design_subtheme/components/rw-user/rw-user-bookmarks.css
html/themes/custom/common_design_subtheme/components/rw-user/rw-user.css
html/themes/custom/common_design_subtheme/sass/cd/cd-header/_cd-user-menu.scss
html/themes/custom/common_design_subtheme/templates/form/user-edit-form.html.twig

More style adjustments to user forms, to incorporate the page title on form edit pages, followed by the local tasks.
Some linting and for now, resetting the flow on the user forms where fieldsets have the border-left to prevent a white space between fieldsets.

RW-125 user forms continued

---

config/field.field.taxonomy_term.disaster.field_glide.yml
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/reliefweb_entities.services.yml
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_entities/src/Services/CountryFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/DisasterFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/JobFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/SourceFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/TrainingFormAlter.php
html/modules/custom/reliefweb_form/js/widget.autocomplete.js
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_utility/src/Helpers/TaxonomyHelper.php
html/themes/custom/common_design_subtheme/templates/form/taxonomy-term-edit-form.html.twig

Ticket: RW-121
This adds the form alter services for countries, disasters and sources.

[RW-121] Country, disaster, source forms

---

config/core.entity_view_display.user.user.default.yml
config/field.field.node.blog_post.body.yml
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_entities/src/EntityModeratedInterface.php
html/modules/custom/reliefweb_entities/src/EntityModeratedTrait.php
html/modules/custom/reliefweb_entities/src/Services/JobFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/TrainingFormAlter.php
html/modules/custom/reliefweb_entities/templates/reliefweb-entities-form-user-information.html.twig
html/modules/custom/reliefweb_moderation/reliefweb_moderation.module
html/modules/custom/reliefweb_moderation/src/Helpers/UserPostingRightsHelper.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceInterface.php
html/modules/custom/reliefweb_moderation/src/Services/AnnouncementModeration.php
html/modules/custom/reliefweb_moderation/src/Services/BlogPostModeration.php
html/modules/custom/reliefweb_moderation/src/Services/BookModeration.php
html/modules/custom/reliefweb_moderation/src/Services/CountryModeration.php
html/modules/custom/reliefweb_moderation/src/Services/DisasterModeration.php
html/modules/custom/reliefweb_moderation/src/Services/JobModeration.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/modules/custom/reliefweb_moderation/src/Services/SourceModeration.php
html/modules/custom/reliefweb_moderation/src/Services/TopicModeration.php
html/modules/custom/reliefweb_moderation/src/Services/TrainingModeration.php
html/modules/custom/reliefweb_subscriptions/src/ReliefwebSubscriptionsMailer.php
html/modules/custom/reliefweb_utility/src/Helpers/DateHelper.php
html/modules/custom/reliefweb_utility/src/Helpers/TextHelper.php

Ticket: RW-171
This adds the entity access and presave handling for the moderation services and fixes several issues with the form alter services.
This also ports text field cleaning to remove control characters, consecutive spaces etc.

[RW-171] Moderation and fixes

---

config/workflows.workflow.job.yml
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_moderation/src/EntityModeratedTrait.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceInterface.php
html/themes/custom/common_design_subtheme/templates/form/node-edit-form--training.html.twig

Ticket: RW-203
This uses the proper property to get the moderation status from the form state object + a few other tiny fixes.

[RW-203] Fix moderation status handling in forms

---

html/modules/custom/reliefweb_entities/templates/reliefweb-entities-form-user-information.html.twig
html/themes/custom/common_design_subtheme/components/rw-user-information/rw-user-information.css

Display user information stacked vertically, display labels, and sources as comma-separated when multiple.

RW-127 User information

---

html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_form/js/widget.autocomplete.js

Ticket: RW-179
This fixes the logic to handle the selection of disasters via the autocomplete widget.

[RW-179] Fix disaster autocomplete handling

---

html/modules/custom/reliefweb_fields/components/reliefweb-links/reliefweb-links.css
html/modules/custom/reliefweb_fields/components/reliefweb-user-posting-rights/reliefweb-user-posting-rights.css
html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
html/themes/custom/common_design_subtheme/components/rw-page-title/rw-page-title.css

RW-243
1. Set font-size for User posting rights ul to match D7
2. Vertical rhythm for User posting rights form following page title
3. Fix typo in page title
RW-244
1. Set display and overflow to control alt text display

RW-243 user posting rights and RW-244 image alt text display

---

html/modules/custom/reliefweb_entities/src/Entity/Source.php
html/modules/custom/reliefweb_entities/src/SectionedContentTrait.php
html/modules/custom/reliefweb_rivers/src/Services/SourceRiver.php
html/modules/custom/reliefweb_utility/src/Helpers/LocalizationHelper.php
html/modules/custom/reliefweb_utility/tests/src/Unit/LocalizationHelperNumberFormatTest.php
html/modules/custom/reliefweb_utility/tests/src/Unit/Stub/LocalizationHelperStub.php
html/modules/custom/reliefweb_utility/tests/src/Unit/Stub/LocalizationHelperStubNoNumberFormatter.php

Ticket: RW-105
This adds a method to the localization helper to format numbers and use it for the organization river and individual pages for the number of publications.

[RW-105] Localized number formatting.

---

composer.lock
html/themes/custom/common_design_subtheme/components/rw-article/rw-article.css
html/themes/custom/common_design_subtheme/components/rw-form/rw-form--widget.css
html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
html/themes/custom/common_design_subtheme/components/rw-revisions/rw-revisions.css
html/themes/custom/common_design_subtheme/templates/content/node--full.html.twig

1. Update base theme branch with latest commits from https://github.com/UN-OCHA/common_design/pull/254
2. Adjust more rules in `rw-form` component due to changes in the `cd-form` component in base theme
3. Template override for generic full node to use for Announcement content type
4. Add bottom margin for Announcement page title
5. Add top margin for revisions

RW-31 more QA, update base theme

---

html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/common_design_subtheme/components/rw-guidelines/rw-guidelines.css

The close icon wasn't quite right and I've extended the `reliefweb_form/form.guidelines` with the component in the sub theme.

RW-258 Guidelines

---

html/modules/custom/reliefweb_moderation/src/Services/SourceModeration.php

[RW-256] Fix source presave to set user posting rights to blocked

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/rw-moderation/rw-moderation.css
html/themes/custom/common_design_subtheme/components/rw-people/rw-people.css
html/themes/custom/common_design_subtheme/templates/form/form--reliefweb-users-form.html.twig

RW-286 people page

---

html/modules/custom/reliefweb_docstore/reliefweb_docstore.module
html/modules/custom/reliefweb_docstore/src/Plugin/Field/FieldType/ReliefWebFile.php
html/modules/custom/reliefweb_utility/src/Helpers/LegacyHelper.php
html/modules/custom/reliefweb_utility/src/Response/JsonResponse.php

https://humanitarian.atlassian.net/browse/RW-295
All are in code comments apart from the 'valyes' variable.

[RW-295] fix small typos

---

html/modules/custom/reliefweb_subscriptions/README.md

Adjust drush command for accuracy

[RW-132] Subscriptions readme

---

composer.json
composer.lock

Ticket: RW-317
Update the api-indexer with the fix for the images.

[RW-317] Fix indexing of images

---

composer.json
composer.lock
config/reliefweb_api.settings.yml
html/modules/custom/reliefweb_api/config/install/reliefweb_api.settings.yml
html/modules/custom/reliefweb_api/config/schema/reliefweb_api.schema.yml
html/modules/custom/reliefweb_api/reliefweb_api.module
html/modules/custom/reliefweb_api/src/Commands/ReliefWebApiCommands.php
html/modules/custom/reliefweb_docstore/reliefweb_docstore.module
html/modules/custom/reliefweb_docstore/src/Commands/ReliefWebDocstoreCommands.php
html/modules/custom/reliefweb_migrate/drush.services.yml
html/modules/custom/reliefweb_migrate/src/Commands/ReliefWebMigrateCommands.php
html/modules/custom/reliefweb_utility/src/Helpers/UrlHelper.php

Add option to simulate indexing and disable replica.
Add image download drush command
Download previews when migrating files

[RW-251][RW-291][RW-296] Fixes and improvements

---

html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-river.html.twig
html/themes/custom/common_design_subtheme/components/rw-pager/rw-pager.css
html/themes/custom/common_design_subtheme/components/rw-river/rw-river.css
html/themes/custom/common_design_subtheme/templates/navigation/pager.html.twig

This moves the pager outside the list section element and adjusts the styles for its display. It also changes the pager nav title from a h3 to h2 to reflect the change in hierarchy.

RW-316 Pager

---

composer.lock
html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
html/themes/custom/common_design_subtheme/components/rw-guidelines/rw-guidelines.css
html/themes/custom/common_design_subtheme/components/rw-moderation/rw-moderation.css
html/themes/custom/common_design_subtheme/components/rw-search/rw-search.css
html/themes/custom/common_design_subtheme/components/rw-toc/rw-toc.css

RW-285 (See issue - this was undone after some discussion because a better solution was found)
RW-323
RW-324
RW-321
RW-322

Frontend adjustments based on testing

---

composer.json
composer.lock
config/reliefweb_api.settings.yml
html/modules/custom/reliefweb_api/config/install/reliefweb_api.settings.yml
html/modules/custom/reliefweb_api/config/schema/reliefweb_api.schema.yml
html/modules/custom/reliefweb_api/reliefweb_api.module
html/modules/custom/reliefweb_api/src/Commands/ReliefWebApiCommands.php
symfony.lock

Ticket: OPS-8064
Sister PR of https://github.com/UN-OCHA/rwint-api-indexer/pull/32
TODO:

[OPS-8064] Change replicas and shards ES settings

---

html/themes/custom/common_design_subtheme/components/rw-form/rw-form--widget.css

RW-340 add break-all rule for filename links

---

html/themes/custom/common_design_subtheme/components/rw-moderation/rw-moderation.css

RW-345 add focus style to create button

---

html/modules/custom/reliefweb_homepage/components/headlines-widget/headlines-widget.js
html/modules/custom/reliefweb_homepage/reliefweb_homepage.module
html/modules/custom/reliefweb_migrate/src/Plugin/migrate/source/UrlAlias.php
html/modules/custom/reliefweb_utility/reliefweb_utility.module

- RW-390 Update headline selection when a report is unpublished, deleted or not an headline anymore
- RW-391 Refactor drag and drop logic for headline widget on homepage to be snappier
- RW-392 Do not change file URIs to UUID based pattern for temporary files
- RW-393 Fix migration of entity redirects

Various fixes - part 7

---

html/modules/custom/reliefweb_import/src/Command/ReliefwebImportCommand.php
html/modules/custom/reliefweb_import/tests/src/Unit/ReliefwebImporterStringTest.php
html/modules/custom/reliefweb_import/tests/src/Unit/Stub/ReliefwebImportCommandStub.php
html/modules/custom/reliefweb_utility/src/Helpers/HtmlSanitizer.php

Ticket: RW-238
This improves handling of text fields when importing jobs and add more tests

[RW-238] Job import

---

config/core.extension.yml
config/google_tag.container.default.yml
config/google_tag.settings.yml
html/modules/custom/reliefweb_analytics/README.md
html/modules/custom/reliefweb_analytics/reliefweb_analytics.info.yml
html/modules/custom/reliefweb_analytics/reliefweb_analytics.module
html/modules/custom/reliefweb_guidelines/drush.services.yml
html/modules/custom/reliefweb_guidelines/src/Commands/ReliefWebGuidelinesCommands.php

- [RW-189] Add custom GTM dimensions
- [RW-423] Add authorization header to download trello images
[RW-189]: https://humanitarian.atlassian.net/browse/RW-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RW-423]: https://humanitarian.atlassian.net/browse/RW-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Various fixes - part 14

---

docker/etc/nginx/apps/drupal/drupal.conf
html/modules/custom/reliefweb_dsr/src/Services/DSRClient.php
html/modules/custom/reliefweb_rivers/js/advanced-search.js
html/modules/custom/reliefweb_rivers/src/AdvancedSearch.php
html/themes/custom/common_design_subtheme/components/rw-advanced-search/rw-advanced-search.css

- RW-234: catch guzzle exceptions for DSR
- RW-255: show datepicker when pressing key in advanced search
- RW-424: fix nginx 404 on /help/* paths
- RW-436: add cancel and select buttons to datepicker in advanced search

Various fixes - part 17

---

composer.lock
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_fields/components/reliefweb-links/reliefweb-links.css
html/modules/custom/reliefweb_fields/components/reliefweb-links/reliefweb-links.js
html/modules/custom/reliefweb_fields/components/reliefweb-user-posting-rights/reliefweb-user-posting-rights.js
html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebLinks.php
html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebSectionLinks.php
html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebUserPostingRights.php
html/themes/custom/common_design_subtheme/components/rw-form/rw-form.css
symfony.lock

- RW-149 fix compatibility with term previews and profile and user posting rights fields
- RW-437 fix file indexing in API
- RW-439 fix revision user id for terms

 Various fixes - part 18

---

html/modules/custom/reliefweb_docstore/src/Commands/ReliefWebDocstoreCommands.php

- Option to download previews only
- Option to copy local files instead of downloading

[RW-45] Additional options for file migration

---

config/imagemagick.settings.yml
config/system.image.yml
html/modules/custom/reliefweb_docstore/src/Controller/FileDownloadController.php
html/modules/custom/reliefweb_docstore/src/Services/DocstoreClient.php
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/src/Entity/Training.php
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/themes/custom/common_design_subtheme/components/rw-moderation/rw-moderation.css

- RW-45: close file resources after usage
- RW-456: open entity clone form in new tab
- RW-458: prevent saving ongoing training as expired
- RW-460: fix order of entity form submit callbacks to solve issue with potential new sources
- RW-465: enable imagick as image toolkit
- RW-466: fix date used in moderation backend

Various fixes - part 19

---

composer.lock
html/modules/custom/reliefweb_api/src/Commands/ReliefWebApiCommands.php
html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_homepage/src/Controller/Homepage.php
html/themes/custom/common_design_subtheme/components/rw-datepicker/rw-datepicker.css
symfony.lock

- RW-457: get list of references for api indexing command from indexer
- RW-470: change description of file field to PDF only
- RW-472: fix styling issue with datepicker
- RW-473: fix caching of homepage block
- RW-474: fix indexing of disaster property for reports

Various fixes - part 20

---

composer.lock
html/themes/custom/common_design_subtheme/templates/navigation/menu--help.html.twig

- Update base theme to v 7.0.1
- Update help menu partial

RW-487 base theme update

---

composer.lock
docker/etc/nginx/custom/01_attachment_redirections.conf
html/modules/custom/reliefweb_docstore/reliefweb_docstore.module
html/modules/custom/reliefweb_docstore/src/Plugin/Field/FieldType/ReliefWebFile.php
html/modules/custom/reliefweb_docstore/src/Plugin/Field/FieldWidget/ReliefWebFile.php
html/modules/custom/reliefweb_rivers/src/Services/ReportRiver.php

- RW-457: Add parameter to preview image URLs to bust browser cache
- RW-483: Fix issue with replaced file URL
- RW-488: Return a 404 when connection to the docstore fails

[RW-457][RW-483][RW-488] Files

---

Makefile
tests/docker-compose.yml

Refs: OPS-8219
Making this change to all the repos, as decided in https://github.com/UN-OCHA/gho-stack/pull/4#discussion_r877713366

chore: rename local image for consistency

---

html/modules/custom/reliefweb_subscriptions/drush.services.yml
html/modules/custom/reliefweb_subscriptions/src/Command/ReliefwebSubscriptionsSendCommand.php

refactor: Do not use state State api, as it cannot be populated via settings.php

---

html/themes/custom/common_design_subtheme/components/rw-user/rw-user.css

- add selector for unsubscribe form checkbox items
- space out cancel button from save button
As I cannot see this page locally, I did what I could in the browser using Prod.
Expected results:

RW-573 Checkbox layout on unsubscribe form for logged out users

---

html/modules/custom/reliefweb_subscriptions/src/Form/SubscriptionForm.php

bug: Unsubscribe countries

---

composer.json
composer.lock

fix: Use the packagisted versions of the RW libraries, so we do not get git auth issues during test or build.

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/Services/JobModeration.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/modules/custom/reliefweb_moderation/src/Services/TrainingModeration.php

[RW-583] Revision log filter in moderation backend

---

html/modules/custom/reliefweb_revisions/src/EntityRevisionedTrait.php

[RW-580] Fix revision not showing in revision table

---

composer.json
composer.lock
html/modules/custom/reliefweb_analytics/drush.services.yml
html/modules/custom/reliefweb_analytics/reliefweb_analytics.module
html/modules/custom/reliefweb_analytics/src/Command/ReliefwebMostReadCommand.php
symfony.lock

feat: Fetch data

---

config/core.entity_view_display.media.image_blog_post.media_library.yml
config/core.entity_view_display.media.image_book.media_library.yml
config/core.entity_view_display.media.image_source.media_library.yml
config/core.entity_view_display.media.image_topic.media_library.yml
html/themes/custom/common_design_subtheme/components/rw-form/rw-form--widget.css

[RW-551] fix thumbnails in media library widget

---

docker/Dockerfile
scripts/light-dump.sh

Refs: OPS-8360
Script that generates a DB sql dump file, only keeping the most recent jobs, training and reports.

[WIP][OPS-8360] feat: add script to generate lighter DB dump

---

config/block.block.soft_footer.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/rw-cd-header-footer/cd-soft-footer.css
html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-soft-footer.html.twig
html/themes/custom/common_design_subtheme/templates/layout/page--403.html.twig
html/themes/custom/common_design_subtheme/templates/layout/page--404.html.twig
html/themes/custom/common_design_subtheme/templates/layout/page--node--edit.html.twig
html/themes/custom/common_design_subtheme/templates/layout/page.html.twig

RW-589 Soft Footer with Mailchimp

---

html/modules/custom/reliefweb_migrate/src/Commands/ReliefWebMigrateCommands.php

[RW-558] Legacy redirections

---

html/modules/custom/reliefweb_meta/reliefweb_meta.module

RW-600 Metadata for Reports and Jobs

---

config/social_auth_hid.settings.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/rw-document/rw-document.css
html/themes/custom/common_design_subtheme/js/login_destination.js

Cherry picked from https://github.com/UN-OCHA/rwint9-site/pull/382 so we can merge without the most read work.

[RW-599] Intermediary login page

---

.travis.yml
tests/docker-compose.yml
tests/settings/settings.test.php
tests/test.sh

feat: No more redis, also use memcache in tests

---

composer.json
composer.lock
html/modules/custom/reliefweb_analytics/README.md
html/modules/custom/reliefweb_analytics/drush.services.yml
html/modules/custom/reliefweb_analytics/reliefweb_analytics.module
html/modules/custom/reliefweb_analytics/src/Command/ReliefwebMostReadCommand.php
html/modules/custom/reliefweb_entities/src/SectionedContentTrait.php
html/modules/custom/reliefweb_homepage/src/Controller/Homepage.php
symfony.lock

feat: Most read

---

config/core.entity_form_display.node.job.default.yml

bug: job categories

---

html/modules/custom/reliefweb_form/js/widget.selectionlimit.js

bug: check disabled

---

html/modules/custom/reliefweb_migrate/src/Commands/ReliefWebMigrateCommands.php
html/modules/custom/reliefweb_user_posts/src/Services/UserPostsService.php

Sneaked in a fix for a drush command so that we don't get a warning when running drush cc. This issue had no effect and the command was already run.

[RW-602] Bug fixes

---

html/modules/custom/reliefweb_fields/src/Plugin/CKEditorPlugin/ReliefWebFormattedText.php
html/modules/custom/reliefweb_files/src/Controller/FileDownloadController.php
html/modules/custom/reliefweb_guidelines/src/Controller/GuidelineSinglePageController.php
html/modules/custom/reliefweb_migrate/src/Commands/ReliefWebMigrateCommands.php
html/modules/custom/reliefweb_migrate/src/Entity/AccumulatedSqlContentEntityStorageTrait.php
html/modules/custom/reliefweb_migrate/src/EventSubscriber/ProxySubscriber.php
html/modules/custom/reliefweb_utility/src/Helpers/MarkdownHelper.php
html/modules/custom/reliefweb_xmlsitemap/drush.services.yml
html/modules/custom/reliefweb_xmlsitemap/src/Command/ReliefwebXmlsitemapCommand.php

Refs: RW-609
Ran [Drupal check](https://github.com/mglaman/drupal-check) against the custom code and replaced the deprecated functions, classes etc.

[RW-609] Replace deprecations

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_form/reliefweb_form.module

bug: Remove custom attributes on inputs

---

composer.lock

[RW-610] Update api-indexer

---

html/modules/custom/reliefweb_analytics/src/Command/ReliefwebMostReadCommand.php

Refs: RW-23
This is a PR against the branch of https://github.com/UN-OCHA/rwint9-site/pull/394
It contains fixes (for example, the PR above was sorting by weight ascending) and adjusts the formula because the `activeXDayUsers` don't return what we want.
This [article](https://support.google.com/analytics/answer/6171863?hl=en#zippy=%2Cin-this-article) explains what those metrics actually mean: the number of users within X days from the start date of the date range which kind of makes sense for an advertisement where one may want to know if a campaign launch was successful but is kind of the opposite of what we want.
However the google API offers a way to get what we need to boost more recently viewed documents via the use of multiple date ranges (max 4).
That gives us the following …

[RW-23] Adjust scoring formula for most read content

---

html/modules/custom/reliefweb_analytics/README.md
html/modules/custom/reliefweb_analytics/src/Command/ReliefwebMostReadCommand.php

feat: Use active28DayUsers for sorting

---

html/modules/custom/reliefweb_users/reliefweb_users.module
html/modules/custom/reliefweb_users/src/Controller/UserEmailConfirmationController.php

[RW-586] Change user landing page tab title

---

html/modules/custom/reliefweb_moderation/reliefweb_moderation.module
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_revisions/src/Services/EntityHistory.php
html/modules/custom/reliefweb_utility/src/Helpers/EntityHelper.php
html/modules/custom/reliefweb_utility/src/Helpers/MarkdownHelper.php

[RW-581] Consolidate formatting of revision log message

---

html/modules/custom/reliefweb_moderation/templates/reliefweb-moderation-table.html.twig

[RW-617] Fix spelling of buried

---

html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFile.php

[RW-524] Prevent refocusing after file upload

---

html/modules/custom/reliefweb_migrate/src/Commands/ReliefWebMigrateCommands.php

Refs: RW-560
During the initial migration, only the current revision record was migrated for files to ensure we only had the latest data. The side effect is that it looks like the files were attached by the last person who created a revision. This migrates the other file field revisions for existing files so that the history shows properly when they were attached.

[RW-560] Add drush command to migrate file revisions

---

composer.lock
composer.patches.json

Refs: OPS-8466, OPS-8467, OPS-8468, OPS-8469

chore: update core to 9.4.3, and dependencies

---

html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php

chore: add missing comment to method

---

html/modules/custom/reliefweb_revisions/src/Services/EntityHistory.php

[RW-631] Clear revision history when media is changed

---

html/themes/custom/common_design_subtheme/components/rw-cd-header-footer/cd-soft-footer.css
html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-soft-footer.html.twig

RW-647 Mailchimp form accessibility fixes

---

composer.lock

chore: update api-indexer

---

composer.lock
html/modules/custom/reliefweb_files/templates/reliefweb-file-list--interactive.html.twig
html/modules/custom/reliefweb_files/templates/reliefweb-file-list.html.twig

- RW-678: fix twig exception issue with files with an invalid preview

Develop -> Main - v1.4.1

---

config/core.extension.yml
html/modules/custom/reliefweb_reporting/README.md
html/modules/custom/reliefweb_reporting/drush.services.yml
html/modules/custom/reliefweb_reporting/reliefweb_reporting.info.yml
html/modules/custom/reliefweb_reporting/src/Commands/ReliefWebReportingCommands.php

Refs: RW-528
This adds a custom module with some drush commands to send posting statistics to replace logic in jenkins jobs.

[RW-528] Add reporting module to send posting stats

---

html/modules/custom/reliefweb_meta/reliefweb_meta.module

[RW-687] fix updates river head title

---

composer.lock

Refs: RW-653
This updates the API indexer to use the new version that converts the topic disaster maps.

[RW-653] Update api-indexer

---

composer.lock

Refs: RW-648.
This updates the autocomplete library with the tiny accessibility fix.

[RW-649] Update autocomplete library

---

composer.lock
html/modules/custom/reliefweb_utility/src/Plugin/Filter/IFrameFilter.php
html/modules/custom/reliefweb_utility/tests/src/Unit/IFrameFilterTest.php

Refs: RW-699
This fixes the iframe conversion when the URL is empty and trims it.

[RW-699] Fix iframe conversion

---

html/modules/custom/reliefweb_rivers/js/advanced-search.js
html/modules/custom/reliefweb_rivers/src/AdvancedSearch.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-advanced-search.html.twig

[RW-697] Accessibility

---

html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-ocha.html.twig

chore: update related platforms list to remove HRInfo and replace with RWR
Refs: RW-715

RW-715 Update OCHA Services Related Platforms list

---

html/modules/custom/reliefweb_user_posts/src/Services/UserPostsService.php

Refs: RW-723
This fixes the logic of the my posts page when the user is blocked for a source to display all the user's ads except the ones from sources the user is blocked for.
*Pro tip: log in with the normal user in a normal window and log in with an editor with a private window to avoid logging in and out several times*
1. Log in as a normal user (create a dummy one for example)
2. Create 2 jobs with different sources
3. Log in as an editor, edit the user posting rights for the sources above and set the previous user as allowed for one and blocked for the other source
4. Log in back as the normal user
5. Check your "My Posts" page (/user/xxxx/posts)
6. You should **only** see the ad for the source the user is blocked for
7. Check the user's posts …

[RW-723] Logic fix for my posts page for blocked sources

---

html/themes/custom/common_design_subtheme/components/rw-document/rw-document.css
html/themes/custom/common_design_subtheme/components/rw-opportunities/rw-opportunities.css

RW-731 Break anchors to prevent overflow

---

html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFile.php

fix: serialization issue with the reliefweb file widget

---

docker/Dockerfile

chore: update dockerfile

---

html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-soft-footer.html.twig

Refs: RW-749
Related Trello card: https://trello.com/c/POYWMwx2/995-change-the-text-in-the-footer-refer-only-to-the-blog

chore: change text for subscription form

---

docker/Dockerfile

chore: use standard image for builder

---

html/modules/custom/reliefweb_api/src/Services/ReliefWebApiClient.php

[RW-759] Fix api filter optimization for ranges

---

composer.json
composer.lock

feat: update API indexer to index redirects field

---

composer.json
composer.lock

chore: remove preserve-paths dependency as it's broken and no longer

---

docker/etc/nginx/custom/03_mapbox.conf

fix: SSL connection to mapbox

---

README.md
scripts/retagging/README.md
scripts/retagging/RW-719.php
scripts/retagging/RW-720.php
scripts/retagging/RW-765.php
scripts/retagging/RW-766.php
scripts/retagging/RW-767.php

Refs: RW-719, RW-720, RW-765, RW-766, RW-767
Update README with workflow for retagging content and store retagging scripts for reference.

chore: retagging scripts

---

scripts/retagging/RW-768.php
scripts/retagging/RW-769.php

chore: retagging scripts for RW-768 and RW-769

---

.github/workflows/run-tests.yml

chore: add permissions so dependabot tests pass

---

scripts/retagging/RW-786.php

[RW-786] Script to remove origin URL of OCHA documents

---

html/modules/custom/reliefweb_api/src/Commands/ReliefWebApiCommands.php

[RW-787] Add option to index all resources at once

---

html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php

[RW-788] Add original publication date filter in report moderation backend

---

scripts/retagging/RW-786.php

fix: origin URL removal script for OCHA documents

---

scripts/light-dump.sh

[RW-735] Update light dump script to include nodes necessary for the API tests

---

scripts/retagging/RW-791.php

[RW-791] Script to remove the HR.info origin URLs

---

html/modules/custom/reliefweb_rivers/src/Services/ReportRiver.php

[RW-790] Fix headline alt tag

---

.gitignore
README.md
local/.env.example
local/README.md
local/docker-compose.yml
local/exec.sh
local/install.sh
local/shared/settings/services.yml
local/shared/settings/settings.local.php
local/shared/settings/settings.memcache.php
local/shared/settings/settings.site.php.example

Refs: RW-785
This is against the branch for the D10 upgrade of RW which should become mainstream soon.
Local stack inspired by and improving on the https://github.com/UN-OCHA/drupal-starterkit one.

[RW-785] Local stack

---

tests/docker-compose.yml
tests/test.sh

[RW-799] Update script to run tests locally

---

local/docker-compose.yml

[RW-807] Change port for mailpit local service to work with caddy

---

docker/etc/nginx/custom/03_mapbox.conf
html/modules/custom/reliefweb_utility/reliefweb_utility.module
html/modules/custom/reliefweb_utility/src/Entity/ImageStyleWithPipeline.php

- [RW-816] Ensure webp deletion.
[RW-816]: https://humanitarian.atlassian.net/browse/RW-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Develop -> Main - v2.1.1

---

html/modules/custom/reliefweb_meta/reliefweb_meta.module

fix: handle entities (ex: remote jobs) without a country for og:image

---

html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-ocha.html.twig

This updates the OCHA Services override to replace Hum Insight with Hum Aciton
Refs: RW-886

RW-886 Replace hum insight with hum action link in OCHA Services

---

html/modules/custom/reliefweb_homepage/templates/reliefweb-homepage-opportunities.html.twig
html/themes/custom/common_design_subtheme/components/rw-homepage/rw-homepage--grid.css
html/themes/custom/common_design_subtheme/components/rw-opportunities/rw-opportunities.css

chore: fix a typo

---

composer.lock

[RW-893] Update ocha_ai module

---

composer.lock

Refs: RW-921
Latest version of the `ocha_ai` module with styling fixes for the chat.

[RW-921] Update ocha_ai module

---

composer.json
composer.lock
config/ocha_ai_chat.settings.yml

- Contains the Chat UI improvements from this week.
- Config to set feedback mode to `both`
- Contains formatting improvements to Chai UI
- Config to set formatting to `basic`
- Check out branch, `composer install`, `drush cim`
- Navigate to an Update that shows the chat button, activate, and ask a question.
- You should see the new UI that includes the words "Give detailed feedback" under the answer.
- If you give a prompt such as "Give me three talking points" it should spit out a formatted answer with line breaks.
- Copying the answer to clipboard should retain line breaks.

[RW-928][RW-930] Bump ocha_ai module

---

docker/etc/nginx/apps/drupal/drupal.conf

Refs: OPS-9780
Same changes as https://github.com/UN-OCHA/docker-images/pull/357. See this PR's description for details.

[OPS-9780] Fix nginx locations for files

---

html/modules/custom/reliefweb_api/README.md
local/docker-compose.yml
local/shared/settings/settings.local.php

Refs: local dev
Plus a typo and removing an obsolete line from docker-compose.yml

chore: local settings

---

html/themes/custom/common_design_subtheme/templates/cd/cd-footer/cd-ocha.html.twig

[RW-973] Fix: remove duplicate entries in the OCHA services footer

---

config/seckit.settings.yml

Refs: OPS-10398
This implements the changes suggested in the comments of https://github.com/UN-OCHA/rwint9-site/pull/813 on a new branch (for ease of rolling back if necessary)

chore: revise csp config

---

composer.json
composer.lock
config/core.extension.yml
config/seckit.settings.yml
html/themes/custom/common_design_subtheme/templates/rw-modules/reliefweb_entities/reliefweb-entities-entity-text.html.twig
tests/vrt/urls_anon.txt

feat: Add seckit

---

config/seckit.settings.yml

bug: Allow calls to API

---

html/modules/custom/reliefweb_job_tagger/src/Plugin/QueueWorker/OchaAiJobTagTaggerWorker.php

Refs: RW-954
A proposal to show the combined stats and to normalize the scores. See the reasoning in the comment line 306-316.

chore: show combined feedback stats and normalize scores

---

html/modules/custom/reliefweb_job_tagger/src/Plugin/QueueWorker/OchaAiJobTagTaggerWorker.php

bug: div by zero

---

scripts/retagging/RW-993.php

[RW-994] Script to retag UNCT Columbia to EHP

---

composer.json
composer.lock
config/core.extension.yml
config/honeypot.settings.yml

Refs: RW-1007
Enable honeypot module. This uses default settings - it will be added to ocha_ai form in that module.

chore: add honeypot module

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module

[RW-1005] Catch exception when there is no route found when checking block access for the chat

---

PATCHES/jsonlog--3460929--elastic-direct-logging.patch

[RW-1005] Update jsonlog patch

---

config/seckit.settings.yml

chore: add another domain for csp

---

composer.lock
html/modules/custom/reliefweb_job_tagger/config/install/reliefweb_job_tagger.settings.yml
html/modules/custom/reliefweb_job_tagger/reliefweb_job_tagger.module
html/modules/custom/reliefweb_job_tagger/src/Form/RwJobTaggerRequeueForm.php
html/modules/custom/reliefweb_job_tagger/src/Plugin/QueueWorker/OchaAiJobTagTaggerWorker.php

bug: Fix logic of re-queueing

---

html/modules/custom/reliefweb_job_tagger/reliefweb_job_tagger.module

feat: Embed using structured data

---

composer.json
composer.lock
config_dev/stage_file_proxy.settings.yml

[RW-1042] Update stage file proxy

---

.github/workflows/run-tests.yml

Also show the docker version, for good measure.
Refs: OPS-10706

feat: Show PHP (and Drupal) errors on fail.

---

composer.lock

Refs: RW-1019, RW-1037, RW-1047

[RW-1019][RW-1037][RW-1047] Update ocha_ai module to 1.5.0

---

PATCHES/core--drupal--3467860-aggregation.patch
composer.json
composer.lock
config/ocha_ai.settings.yml
config/ocha_ai_chat.settings.yml

Manual composer update.
Some of the main changes:
- Drupal 10.3.5 with js/css aggregation patch update
- OCHA AI 1.6.1 with settings update
- Honeypot downgrade to 2.1.4 due to https://www.drupal.org/project/honeypot/issues/3468450

Composer update

---

config/honeypot.settings.yml

[RW-1040] Reduce time limit for first interaction on chat form

---

config/user.role.authenticated.yml

[RW-1041] Allow authenticated users to access to AI chat

---

config/seckit.settings.yml

[RW-1088] Add powerbi to frame-src

---

html/modules/custom/reliefweb_entities/src/Entity/Report.php
html/modules/custom/reliefweb_entities/tests/src/Unit/Entity/ReportTest.php
html/modules/custom/reliefweb_utility/src/Helpers/ReliefWebStateHelper.php
html/modules/custom/reliefweb_utility/tests/src/Unit/ReliefWebStateHelperTest.php

Refs: RW-1089
This introduces a state variable for the report publication notification message and add some related unit tests.

[RW-1089] Use state variable for the report publication notification message

---

local/docker-compose.yml
tests/docker-compose.yml

[OPS-10917] Ensure we do not hit the rate limits for the tests or local devel

---

html/modules/custom/reliefweb_rivers/css/search-converter.css
html/modules/custom/reliefweb_rivers/js/search-converter.js
html/modules/custom/reliefweb_rivers/reliefweb_rivers.libraries.yml
html/modules/custom/reliefweb_rivers/src/Controller/SearchConverter.php
html/modules/custom/reliefweb_rivers/templates/reliefweb-rivers-search-converter.html.twig

feat: UX of search convertor

---

html/modules/custom/reliefweb_reporting/reliefweb_reporting.info.yml
html/modules/custom/reliefweb_reporting/src/ApiIndexerResource/ReportExtended.php
html/modules/custom/reliefweb_reporting/src/Commands/ReliefWebReportingCommands.php

Refs: RW-1084
This adds a drush command that uses the RW API indexer to get data compatible with the data from the RW API with extra fields like the user ID and origin type.

[RW-1084] Add drush command to export report data

---

html/modules/custom/reliefweb_analytics/src/Command/ReliefwebMostReadCommand.php
html/modules/custom/reliefweb_entities/src/Plugin/EntityReferenceSelection/AnyTermSelection.php

[RW-1091] Prevent deprecation notice

---

html/themes/custom/common_design_subtheme/components/rw-document/rw-document.css

[RW-1092] Hide content format icon in sidebar

---

composer.json
composer.lock
html/modules/custom/reliefweb_reporting/src/Commands/ReliefWebReportingCommands.php

Because using the `gdrive` binary via Jenkins is a PITA.
Refs: OPS-10953

feat: Allow drush to upload reports to GDrive.

---

composer.lock

[RW-1052][RW-1107] Update ocha_ai to 1.7.0

---

composer.lock

Refs: RW-1128
Note that some changes in openid_connect were discarded in the update
process. See ticket for more details.

chore: regular updates

---

html/themes/custom/common_design_subtheme/templates/block/block--system-branding-block.html.twig

[RW-1113] Add dimensions to RW logo

---

composer.lock

[RW-1054] Update ocha_ai module

---

docker/Dockerfile
docker/etc/php83/php.ini

This is to work around lua apparently being broken on Alpine 3.20 now! Eventually the fix will be in the base image and this change can then be rolled back.
Refs: OPS-11226

fix: Ship a custom Dockerfile with configurable cli size limits.

---

html/modules/custom/reliefweb_moderation/js/moderation.js
html/modules/custom/reliefweb_moderation/src/Form/ModerationPageFilterForm.php
html/modules/custom/reliefweb_moderation/src/ModerationServiceBase.php
html/modules/custom/reliefweb_moderation/src/Services/JobModeration.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/modules/custom/reliefweb_moderation/templates/reliefweb-moderation-table.html.twig
html/themes/custom/common_design_subtheme/components/rw-moderation/rw-moderation.css

Refs: RW-1157
- Embargo date filter for reports
- Contributor filter for reports
- Display embargo date for reports
- Automated classification status filter for jobs
- Shortcut to select status for all moderation pages

[RW-1157] QOL improvements for moderation pages

---

html/modules/custom/reliefweb_reporting/src/AutomatedClassificationReporting.php
html/modules/custom/reliefweb_reporting/src/Commands/ReliefWebReportingCommands.php

Refs: RW-1159
This adds a class and drush command to export some data about manually retagged content (jobs).

[RW-1159] Export manually retagged content

---

html/modules/custom/reliefweb_anti_spam/reliefweb_anti_spam.module
html/modules/custom/reliefweb_anti_spam/tests/src/ExistingSite/ReliefWebAntiSpamTest.php
html/modules/custom/reliefweb_anti_spam/tests/src/Unit/ReliefWebAntiSpamTest.php

[RW-1160] Discard submission that have the same content in different fields

---

html/modules/custom/reliefweb_revisions/reliefweb_revisions.module
html/modules/custom/reliefweb_revisions/src/EntityRevisionedInterface.php
html/modules/custom/reliefweb_revisions/src/EntityRevisionedTrait.php
html/modules/custom/reliefweb_revisions/src/Services/EntityHistory.php
html/modules/custom/reliefweb_user_history/src/Entity/User.php

[RW-1162] Clear entity revision history cache when deleting a revision

---

PATCHES/amazon_ses-3417090-cron-queue-14.patch
composer.lock

[OPS-11278] Update amazon_ses and change patch

---

composer.json
composer.lock

chore: remove unused admin theme

---

html/modules/custom/reliefweb_post_api/schemas/v2/job.json

[RW-831] Fix typo in job schema

---

config/user.role.anonymous.yml

[OPS-11184] Save permission for anonymous users to login with entra id direct

---

html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/UnhcrDataImporter.php
html/modules/custom/reliefweb_post_api/src/Plugin/ContentProcessorPluginBase.php

[RW-1174] Improve logging of json schema validation errors

---

html/modules/custom/reliefweb_import/src/Service/JobFeedsImporter.php

[RW-1176] Fix type error in job importer validate city

---

config/ocha_ai.settings.yml

Refs: RW-1173
Add settings for the nova models added in https://github.com/UN-OCHA/ocha_ai/releases/tag/v1.10.0

[RW-1173] Add missing settings for the nova models

---

config/core.entity_form_display.guideline.guideline_list.default.yml
config/core.entity_view_display.guideline.guideline_list.default.yml
config/field.field.guideline.guideline_list.field_role.yml
config/field.storage.guideline.field_role.yml
config/user.role.contributor.yml
html/modules/custom/reliefweb_guidelines/reliefweb_guidelines.module
html/modules/custom/reliefweb_guidelines/reliefweb_guidelines.routing.yml
html/modules/custom/reliefweb_guidelines/src/Controller/GuidelineJsonController.php
html/modules/custom/reliefweb_guidelines/src/Controller/GuidelineSinglePageController.php
html/modules/custom/reliefweb_guidelines/src/Entity/GuidelineList.php
html/modules/custom/reliefweb_guidelines/src/Form/GuidelineListSortForm.php
html/modules/custom/reliefweb_guidelines/src/GuidelineLoadTrait.php
html/modules/custom/reliefweb_guidelines/src/Services/GuidelineListFormAlter.php
html/modules/custom/reliefweb_guidelines/src/Services/GuidelineListModeration.php
html/modules/custom/reliefweb_guidelines/src/Services/GuidelineModeration.php
html/themes/custom/common_design_subtheme/components/cd/cd-header/cd-user-menu.css
html/themes/custom/common_design_subtheme/templates/form/guideline-edit-form--guideline-list.html.twig
scripts/retagging/RW-1179.php

Refs: RW-1179
This adjusts the guidelines system to allow guidelines for contributors.
Post deployment note: run the RW-1179.php script to update the guideline lists.

[RW-1179] Contributor guidelines

---

html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php

[RW-1181] Hide embargo date field for contributors

---

config/system.action.user_add_role_action.topic_editor.yml
config/system.action.user_remove_role_action.topic_editor.yml
config/user.role.topic_editor.yml
html/modules/custom/reliefweb_moderation/src/Services/TopicModeration.php

Refs: RW-1180
This adds a Topic editor role to allow users to edit topics.

[RW-1180] Add role to edit topics

---

html/modules/custom/reliefweb_api/src/Services/ReliefWebApiClient.php

[RW-1182] Ensure proper cache tags for RW API requests

---

local/shared/settings/settings.memcache.php

Refs: OPS-11411
As suggested on https://github.com/UN-OCHA/gms-site/pull/544

updates: update local memcache settings

---

html/modules/custom/reliefweb_subscriptions/src/AmazonSesMessageBuilder.php

[OPS-11445] Prevent unique headers conflict in emails when using ses

---

composer.lock
config/reliefweb_import.plugin.importer.echo_flash_update.yml
config/reliefweb_import.plugin.importer.unhcr_data.yml
html/modules/custom/reliefweb_import/config/schema/reliefweb_import.schema.yml
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/EchoFlashUpdateImporter.php

- RW-1186: Fix regex in ECHO importer
- RW-1186: Update ECHO and UNHCR importer timeouts
- RW-1172: Update ocha_content_classification with fix for permissions when editing content

[RW-1172][RW-1186] v2.28.0 fixes

---

composer.lock
config/core.entity_form_display.node.report.submitter.yml
config/reliefweb_import.plugin.importer.echo_flash_update.yml
config/reliefweb_import.plugin.importer.unhcr_data.yml
config/user.role.submitter.yml
html/modules/custom/reliefweb_ai/reliefweb_ai.module
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/reliefweb_entities.permissions.yml
html/modules/custom/reliefweb_entities/src/Entity/Report.php
html/modules/custom/reliefweb_entities/src/EntityFormAlterServiceBase.php
html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldType/ReliefWebFile.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFile.php
html/modules/custom/reliefweb_files/src/Plugin/Validation/Constraint/ReliefWebFileRealMimeTypeConstraint.php
html/modules/custom/reliefweb_files/src/Plugin/Validation/Constraint/ReliefWebFileRealMimeTypeConstraintValidator.php
html/modules/custom/reliefweb_import/config/schema/reliefweb_import.schema.yml
html/modules/custom/reliefweb_import/reliefweb_import.module
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/EchoFlashUpdateImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/UnhcrDataImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporterPluginBase.php
html/modules/custom/reliefweb_moderation/reliefweb_moderation.permissions.yml
html/modules/custom/reliefweb_moderation/src/EntityModeratedInterface.php
html/modules/custom/reliefweb_moderation/src/EntityModeratedTrait.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/themes/custom/common_design_subtheme/templates/form/node-edit-form--report--submitter.html.twig

Refs: RW-1188, RW-1196, RW-1199, RW-1200
- RW-1196: restrict the data used to calculate the hash of imported content
- RW-1199: fix publication protection for jobs tagged by AI
- RW-1200: improve file validation
- RW-1188: adjust submitter form and permissions

[RW-1196][RW-1199][RW-1200] Fixes and improvements post v2.28.1

---

config/reliefweb_import.plugin.importer.echo_flash_update.yml
config/reliefweb_import.plugin.importer.unhcr_data.yml
html/modules/custom/reliefweb_import/config/schema/reliefweb_import.schema.yml
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporterPluginBase.php

[RW-1199] Fix typo in import config

---

config/core.entity_form_display.node.report.submitter.yml
html/modules/custom/reliefweb_files/config/schema/reliefweb_files.schema.yml
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldType/ReliefWebFile.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFileSimplified.php

[RW-1188] Add settings to reliefweb file field widget simplified to specify max file size and extensions

---

html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php

[RW-1208] Allow editors to edit refused reports

---

html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/InoreaderImporter.php

Refs: RW-1216
Note: from my tests, `ot` accepts microsecond timestamps. That seems to be implied in https://www.inoreader.com/developers/stream-contents when they talk about the `timestampUsec` property.

[RW-1216] Use timestamp of the most recent imported document as starting timestamp for the inoreader feeds

---

html/modules/custom/reliefweb_subscriptions/src/Controller/UnsubscribeController.php

fix(doc): Tssssk.

---

config/reliefweb_import.plugin.importer.inoreader.yml

feat: No AI for theme and disaster type

---

config/user.role.webmaster.yml
html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_entities/reliefweb_entities.permissions.yml
html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/modules/custom/reliefweb_user_posts/src/Services/UserPostsService.php
html/modules/custom/reliefweb_users/reliefweb_users.links.menu.yml
html/modules/custom/reliefweb_users/reliefweb_users.module
html/modules/custom/reliefweb_users/reliefweb_users.permissions.yml
html/modules/custom/reliefweb_users/reliefweb_users.routing.yml
html/modules/custom/reliefweb_users/src/Form/SubmitterAllowedDomainsForm.php

[RW-1214] Assign submitter role to UN people when logging in with Entra ID.

---

html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/InoreaderImporter.php

feat: Add optio to ignore timestamp filters

---

composer.lock

[RW-1222] Update ocha_content_classification

---

composer.lock
docker/Dockerfile
html/modules/custom/reliefweb_post_api/src/Plugin/ContentProcessorPluginBase.php

feat: Convert pdf file containing jpx images

---

html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/InoreaderImporter.php

fix: Make sure we have atr least 1 file for Inoreader

---

html/themes/custom/common_design_subtheme/components/rw-page-title/rw-page-title.css

[RW-1224] Wrap long page titles

---

html/modules/custom/reliefweb_files/js/file.autoupload.js
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFile.php
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFileSimplified.php
html/modules/custom/reliefweb_form/js/file-size-validation.js
html/modules/custom/reliefweb_form/reliefweb_form.libraries.yml
html/modules/custom/reliefweb_form/reliefweb_form.module

[RW-1209] Add client side file size validation when uploading

---

html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/InoreaderImporter.php

bug: Allow multiple classes in html

---

PATCHES/amazon_ses-3446425-token-refresh.patch

fix(stupid): Subtract the counter, not NULL.

---

config/reliefweb_import.plugin.importer.wfp_logcluster.yml

chore: Use documents endpoint

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_files/src/Plugin/Field/FieldWidget/ReliefWebFileSimplified.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/WfpLogClusterImporter.php

Refs: RW-1231, RW-1238, RW-1207

[RW-1231][RW-1238][RW-1207] Minor fixes

---

html/modules/custom/reliefweb_form/js/widget.datepicker.js

[RW-1231] Remove dev leftovers

---

config/reliefweb_import.plugin.importer.echo_map.yml
html/modules/custom/reliefweb_import/README.md
html/modules/custom/reliefweb_import/config/schema/reliefweb_import.schema.yml
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/EchoFlashUpdateImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/EchoMapImporter.php

Refs: RW-1239
ECHO Map importer using their API.

[RW-1239] Add ECHO Map importer

---

html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/EchoMapImporter.php

[RW-12349] ECHO map title fixes

---

html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/EchoMapImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/InoreaderImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/UnhcrDataImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/WfpLogClusterImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporterPluginBase.php
html/modules/custom/reliefweb_post_api/src/Plugin/ContentProcessorPluginBase.php
html/modules/custom/reliefweb_post_api/src/Plugin/ContentProcessorPluginInterface.php
html/modules/custom/reliefweb_post_api/src/Plugin/reliefweb_post_api/ContentProcessor/Report.php

[RW-1237] Pass file bytes to post api processor

---

config/field.field.node.report.field_language.yml
html/modules/custom/reliefweb_ai/reliefweb_ai.module
html/modules/custom/reliefweb_entities/src/Plugin/EntityReferenceSelection/AnyTermSelection.php
html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/modules/custom/reliefweb_rivers/src/Services/ReportRiver.php

[RW-1258] Allow Other as report language

---

html/modules/custom/reliefweb_entities/reliefweb_entities.module
html/modules/custom/reliefweb_import/reliefweb_import.module
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporter/InoreaderImporter.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporterPluginBase.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporterPluginInterface.php
html/modules/custom/reliefweb_import/src/Service/InoreaderService.php

Refs: RW-1268
Follow-up of https://github.com/UN-OCHA/rwint9-site/pull/1151 to allow bypassing the moderation status based on the classification status.

[RW-1268] Add hook to allow bypassing the moderation status based on the classification status

---

html/modules/custom/reliefweb_entities/src/Services/ReportFormAlter.php
html/themes/custom/common_design_subtheme/templates/form/node-edit-form--report.html.twig

[RW-1276] Adjust fields available to contributors

---

composer.json
composer.lock

For instance, in the inoreader importer.

fix: Require dom-crawler if you want to use its classes.

---

html/modules/custom/reliefweb_subscriptions/src/AmazonSesMessageBuilder.php

[RW-1288] Handle base64 encoded email parts

---

html/modules/custom/reliefweb_reporting/src/ApiIndexerResource/ReportExtended.php

[RW-1291] Better granularity in role field in report export

---

html/modules/custom/reliefweb_ai/reliefweb_ai.module
html/modules/custom/reliefweb_fields/src/Plugin/Field/FieldWidget/ReliefWebUserPostingRights.php
html/modules/custom/reliefweb_import/src/Controller/ReliefWebImporterImportRecordsController.php
html/modules/custom/reliefweb_import/src/Controller/ReliefWebImporterStatisticsController.php
html/modules/custom/reliefweb_import/src/Plugin/ReliefWebImporterPluginBase.php
html/modules/custom/reliefweb_import/src/Service/ReliefWebImporterModeration.php
html/modules/custom/reliefweb_moderation/src/Helpers/UserPostingRightsHelper.php
html/modules/custom/reliefweb_moderation/src/Services/ReportModeration.php
html/modules/custom/reliefweb_reporting/reliefweb_reporting.module
html/modules/custom/reliefweb_reporting/src/ApiIndexerResource/ReportExtended.php
html/modules/custom/reliefweb_reporting/src/AutomatedClassificationReporting.php
html/modules/custom/reliefweb_reporting/src/Commands/ReliefWebReportingCommands.php
html/modules/custom/reliefweb_revisions/src/Services/EntityHistory.php
html/modules/custom/reliefweb_subscriptions/src/Controller/SubscriptionAdminForm.php
html/modules/custom/reliefweb_user_history/reliefweb_user_history.module
html/modules/custom/reliefweb_users/src/Controller/UserController.php

[RW-1305] Use new FetchAs enum instead of PDO constants

---

config/field.field.node.job.field_source.yml
config/field.field.node.training.field_source.yml
html/modules/custom/reliefweb_entities/src/Services/JobFormAlter.php
html/modules/custom/reliefweb_entities/src/Services/TrainingFormAlter.php

[RW-1318][RW-1319] Disable potential new source in job/training forms

---

scripts/retagging/RW-1321.php

Refs: RW-1321
For archiving purpose. Already run.

[RW-1321] Script to retag some duplicate sources

---

config/field.field.node.job.field_source.yml

[RW-1318] Change job source description, sync from prod

---

html/modules/custom/reliefweb_form/js/widget.autocomplete.js

[RW-1339] Ensure selected organizations are displayed when editing job/training/report for non editors

---

html/modules/custom/reliefweb_import/src/Service/InoreaderService.php

bug: cast to int

---

html/modules/custom/reliefweb_users/reliefweb_users.module

feat: Only add submitter role if user does not have a role

---

scripts/data/RW-1312.php

[RW-1312] Save script to get content posting data
